import "../assets/fonts/BarlowSemiCondensed-SemiBold.ttf";
import "../assets/fonts/BarlowSemiCondensed-Bold.ttf";
import "../assets/fonts/JetBrainsMono-Medium.ttf";

export global Theme {
    out property <color> background: #211B16;
    out property <color> track: #524437;
    out property <color> value: #F2E6D3;
    out property <color> cap: #41362C;
    out property <color> cap-hover: #4A3D31;
    out property <color> cap-outline: #5F4F4099;
    out property <color> label: #CBB9A0;
    out property <color> disabled: #706252;
    out property <color> disabled-cap: #342B23;
    out property <color> origin-tick: #A8957D;
    out property <string> ui-font: "Barlow Semi Condensed";
    out property <string> value-font: "JetBrains Mono";
}
