#pragma once
#include "Model.h"
#include "../render/WaveDisplay.h"
#include <slint.h>
#include <chrono>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <sstream>
#include <utility>
namespace dandrum::sampler {
namespace binding {
inline slint::SharedString str(std::string_view s){return slint::SharedString(std::string(s).c_str());}
template<class P> using Row=typename decltype(std::declval<P>()->row_data(0))::value_type;
template<class P,class F> auto project(const P& previous,const std::vector<Record>& records,F fill){
 auto model=std::dynamic_pointer_cast<slint::VectorModel<Row<P>>>(previous);
 if(!model)model=std::make_shared<slint::VectorModel<Row<P>>>();
 std::vector<Row<P>> rows;rows.reserve(records.size());for(auto& r:records){Row<P> row{};fill(row,r);rows.push_back(std::move(row));}
 if(model->row_count()!=rows.size()){model->set_vector(std::move(rows));return model;}
 for(std::size_t i=0;i<rows.size();++i)if(model->row_data(i)!=std::optional<Row<P>>(rows[i]))model->set_row_data(i,rows[i]);
 return model;
}
inline auto strings(std::string_view delimited){std::vector<slint::SharedString> out;std::istringstream in{std::string(delimited)};std::string s;while(std::getline(in,s,';'))if(!s.empty())out.push_back(str(s));return std::make_shared<slint::VectorModel<slint::SharedString>>(std::move(out));}
}
// Global-type inference keeps this adapter independent of the application header.
// Create after AppWindow::create(), retain the returned binding for the window lifetime.
template<class Session> class SessionBinding:public std::enable_shared_from_this<SessionBinding<Session>> {
 const Session& session_;
 std::shared_ptr<Model> model_;
 slint::Timer timer_;
 std::shared_ptr<void> windowLifetime_;
 SessionBinding(const Session& session,std::shared_ptr<Model> model):session_(session),model_(std::move(model)){}
public:
 static std::shared_ptr<SessionBinding> create(const Session& session,std::shared_ptr<Model> model=std::make_shared<Model>()){
  auto self=std::shared_ptr<SessionBinding>(new SessionBinding(session,std::move(model)));std::weak_ptr<SessionBinding> weak=self;
  self->session_.on_command([weak](slint::SharedString a,slint::SharedString t,slint::SharedString text,float v){if(auto s=weak.lock()){bool ok=s->model_->command(a.data(),t.data(),text.data(),v);s->refresh();return ok;}return false;});
  self->session_.on_parameter_gesture([weak](slint::SharedString id,int phase,float v){if(auto s=weak.lock()){bool ok=s->model_->gesture(id.data(),phase,v);s->refresh();return ok;}return false;});
  self->session_.on_note_on([weak](int note,int velocity,slint::SharedString source){if(auto s=weak.lock()){bool ok=s->model_->noteOn(note,velocity,source.data());s->refresh();return ok;}return false;});
  self->session_.on_note_off([weak](int note,slint::SharedString source){if(auto s=weak.lock()){s->model_->noteOff(note,source.data());s->refresh();}});
  self->session_.on_release_notes([weak](){if(auto s=weak.lock()){s->model_->releaseNotes();s->refresh();}});
  self->session_.on_slice_source([](const auto& owners,slint::SharedString id){if(owners){owners->track_any_change();for(std::size_t i=0;i<std::min<std::size_t>(owners->row_count(),8192);++i){auto row=owners->row_data(i);if(row&&row->id==id)return row->source;}}return slint::SharedString{};});
  auto spectral=std::make_shared<dandrum::advanced_sampler::WaveDisplayCache>();
  self->session_.on_spectral_preview([weak,spectral](const auto& buckets,bool reversed,float start,float end,slint::Color ink0,slint::Color ink5,slint::Color accentLow,slint::Color accent,slint::Color paper){
   auto binding=weak.lock();if(!binding)return slint::Image{};if(buckets)buckets->track_any_change();auto sourceRows=binding->session_.get_sources();if(sourceRows)sourceRows->track_any_change();auto sourceId=binding->session_.get_selected_source();auto source=binding->model_->find("source",sourceId.data());std::string name=source?source->text("name"):"";std::transform(name.begin(),name.end(),name.begin(),[](unsigned char c){return std::tolower(c);});std::string profile=name.find("amen")!=std::string::npos||name.find("break")!=std::string::npos?"break":name.find("snare")!=std::string::npos?(name.find("soft")!=std::string::npos?"snare-soft":"snare"):name.find("hat")!=std::string::npos?(name.find("open")!=std::string::npos?"hat-open":"hat-closed"):"kick";
   return spectral->image_for_model(buckets,reversed,start,end,ink0,ink5,accentLow,accent,paper,profile);
  });
  self->session_.on_pc_key([weak](slint::SharedString key,bool pressed,bool textInput,bool modified){if(auto s=weak.lock()){bool ok=s->model_->pcKey(key.data(),pressed,textInput,modified);s->refresh();return ok;}return false;});
  self->timer_.start(slint::TimerMode::Repeated,std::chrono::milliseconds(33),[weak](){if(auto s=weak.lock()){s->model_->tick(0.033);s->refresh();}});self->refresh();return self;
 }
 void retainWindow(std::shared_ptr<void> window){windowLifetime_=std::move(window);}
 std::shared_ptr<Model> model()const{return model_;}
 void refresh(){using namespace binding;auto& m=*model_;
#define TEXT_SET(NAME,KEY) session_.set_##NAME(str(m.text(KEY)))
#define NUM_SET(NAME,KEY) session_.set_##NAME(m.number(KEY))
 TEXT_SET(filter_mode,"filter-mode");TEXT_SET(source_query,"source-query");TEXT_SET(source_category,"source-category");NUM_SET(auditioning,"audition");NUM_SET(host_automation,"host-automation");TEXT_SET(selected_history,"selected-history");NUM_SET(history_collapsed,"history-collapsed");TEXT_SET(freeze_state,"freeze-state");TEXT_SET(collapse_state,"collapse-state");TEXT_SET(page,"page");TEXT_SET(state_id,"state-id");TEXT_SET(patch_name,"patch-name");TEXT_SET(current_patch_id,"patch-id");TEXT_SET(status,"status");TEXT_SET(selected_id,"selected-id");NUM_SET(selected_pad,"selected-pad");TEXT_SET(selected_source,"selected-source");TEXT_SET(selected_zone,"selected-zone");TEXT_SET(selected_slice,"selected-slice");TEXT_SET(selected_route,"selected-route");TEXT_SET(selected_modulator,"selected-modulator");TEXT_SET(selected_macro,"selected-macro");TEXT_SET(midi_learn,"midi-learn");NUM_SET(midi_cc,"midi-cc");NUM_SET(mock_failure,"mock-failure");NUM_SET(selected_diagnostic_event,"selected-diagnostic-event");TEXT_SET(diagnostic_reason,"diagnostic-reason");TEXT_SET(voice_policy,"voice-policy");TEXT_SET(voice_steal,"voice-steal");TEXT_SET(same_note,"same-note");NUM_SET(crossfade_width,"crossfade-width");TEXT_SET(crossfade_curve,"crossfade-curve");session_.set_can_undo(m.undoCount()!=0);session_.set_can_redo(m.redoCount()!=0);session_.set_undo_label(str(m.undoLabel()));session_.set_redo_label(str(m.redoLabel()));TEXT_SET(asset_state,"asset-state");TEXT_SET(analysis_state,"analysis-state");TEXT_SET(reload_state,"reload-state");NUM_SET(analysis_progress,"analysis-progress");NUM_SET(analysis_sensitivity,"analysis-sensitivity");NUM_SET(analysis_count,"analysis-count");NUM_SET(snap_zero,"snap-zero");NUM_SET(pending_count,"pending-count");TEXT_SET(selector_mode,"selector-mode");TEXT_SET(selector_axis,"selector-axis");TEXT_SET(selector_source,"selector-source");NUM_SET(take_lock,"take-lock");NUM_SET(no_immediate_repeat,"selector-no-repeat");TEXT_SET(articulation,"articulation");NUM_SET(release_trigger,"release-trigger");NUM_SET(pedal_aware_release,"pedal-aware-release");NUM_SET(zone_clipboard_count,"zone-clipboard-count");TEXT_SET(scope,"scope");TEXT_SET(play_mode,"play-mode");NUM_SET(reversed,"reversed");NUM_SET(region_start,"region-start");NUM_SET(region_end,"region-end");NUM_SET(fade_in,"fade-in");NUM_SET(fade_out,"fade-out");NUM_SET(loop_start,"loop-start");NUM_SET(loop_end,"loop-end");NUM_SET(loop_crossfade,"loop-crossfade");NUM_SET(loop_enabled,"loop-enabled");NUM_SET(root_note,"root-note");NUM_SET(voices,"voices");NUM_SET(voice_limit,"voice-limit");NUM_SET(playhead,"playhead");NUM_SET(output_level,"output-level");TEXT_SET(browser_query,"browser-query");TEXT_SET(browser_category,"browser-category");session_.set_definition_text(str(m.definition()));TEXT_SET(error,"error");NUM_SET(pc_keys,"pc-keys");NUM_SET(octave_base,"octave-base");
#undef TEXT_SET
#undef NUM_SET
 auto selected=m.find("tree",m.text("selected-id"));auto selectedSource=m.find("source",m.text("selected-source"));session_.set_sample_duration(selectedSource?selectedSource->number("duration"):0);session_.set_sample_metadata(str(selectedSource?selectedSource->text("metadata"):""));session_.set_selected_name(str(selected?selected->text("name"):selectedSource?selectedSource->text("name"):m.text("patch-name")));session_.set_selected_kind(str(selected?selected->text("kind"):selectedSource?selectedSource->text("kind"):"patch"));session_.set_selected_metadata(str(selectedSource?selectedSource->text("metadata"):selected?selected->text("detail"):"Silent editor preview"));

 // Inspector contents follow native selection; prepared claims are limited to available metadata.
 std::vector<Record> inspectorRows,inspectorParameters;
 std::string inspectorTitle=selected?selected->text("name"):m.text("patch-name"),inspectorType="Instrument",inspectorIcon="layers";
 auto ir=[&](std::string kind,std::string label,std::string value={},std::string unit={}) -> Record& {
  inspectorRows.push_back(Record{"inspector:"+std::to_string(inspectorRows.size()),{{"kind",kind},{"label",label},{"value",value},{"unit",unit}}});return inspectorRows.back();
 };
 auto heading=[&](std::string label){ir("header",label);};
 auto property=[&](std::string label,std::string value,std::string unit={}){ir("property",label,value,unit);};
 auto action=[&](std::string label,std::string id,std::string target,std::string field={},double amount=0){auto& row=ir("action",label);row.fields["action"]=id;row.fields["target"]=target;row.fields["field"]=field;row.fields["amount"]=std::to_string(amount);};
 auto numberText=[&](double value){std::ostringstream out;out<<value;return out.str();};
 auto routeSourceName=[&](const Record& route){auto source=m.find("modulator",route.text("source"));if(!source)source=m.find("macro",route.text("source"));return source?source->text("name"):route.text("source");};
 auto routeDestinationName=[&](const Record& route){std::string id=route.text("destination");auto parameter=m.parameterInfo(id);if(id=="level")return std::string("Amp gain");if(id=="start-offset")return std::string("Sample start");if(id=="cutoff")return std::string("Filter cutoff");if(id=="resonance")return std::string("Filter resonance");if(id=="drive")return std::string("Filter drive");if(id.starts_with("pad:")){std::string name=id.substr(4);std::replace(name.begin(),name.end(),':',' ');return std::string("Pad ")+name;}return parameter?parameter->text("label"):id;};
 auto routeRow=[&](const Record& route){auto source=m.find("modulator",route.text("source"));auto parameter=m.parameterInfo(route.text("destination"));auto& row=ir("modulation",routeSourceName(route),routeDestinationName(route));row.fields["action"]="route.select";row.fields["target"]=route.id;row.fields["amount"]=route.text("amount");row.fields["slot"]=route.text("slot");row.fields["parameter-id"]=route.text("destination");};
 std::string page=m.text("page");
 if((page=="sample"||page=="slices")&&m.find("history",m.text("selected-history"))){
  auto history=m.find("history",m.text("selected-history"));inspectorTitle=history->text("label");inspectorType="Operation";inspectorIcon="settings";heading(inspectorTitle);
  auto source=m.find("source",history->text("source",m.text("selected-source")));double duration=source?source->number("duration"):1;std::string operation=history->text("label");std::transform(operation.begin(),operation.end(),operation.begin(),[](unsigned char c){return std::tolower(c);});
  if(operation=="fade"||operation=="fade-in"||operation=="fade-out"){property("In",numberText(m.number("fade-in")*duration*1000),"ms");property("In curve",source?source->text("fade-in-curve","Exponential"):"Exponential");property("Out",numberText(m.number("fade-out")*duration*1000),"ms");property("Out curve",source?source->text("fade-out-curve","Linear"):"Linear");}
  else if(operation=="normalize"){property("Target",history->text("target","-1.0"),"dBFS");property("Mode",history->text("mode","Peak"));property("Gain applied",history->text("gain-applied","Not analysed"),history->fields.contains("gain-applied")?"dB":"");}
  else if(operation=="trim"){if(page=="slices"){property("Start",numberText(m.number("region-start")*duration),"s");property("End",numberText(m.number("region-end")*duration),"s");}else {property("Length",numberText((m.number("region-end")-m.number("region-start"))*duration),"s");property("Snap",m.number("snap-zero")?"Zero crossings":"Off");ir("text","","Edit start and end in the Region fields, or drag the region edges on the waveform.");}}
  else if(operation=="loop"){property("Start",numberText(m.number("loop-start")*duration),"s");property("End",numberText(m.number("loop-end")*duration),"s");property("Crossfade",numberText(m.number("loop-crossfade")*duration*1000),"ms");property("Mode",m.text("play-mode"));}
  else if(operation=="source"){property("File",source?source->text("name"):history->text("detail"));property("Format",source?source->text("metadata"):"Unavailable");property("Length",numberText(duration),"s");action("Replace…","asset.replace",source?source->id:m.text("selected-source"));}
  else if(operation=="slice"){property("Method",history->text("method","Even"));property("Count",std::to_string(m.records("slice").size()));property("Snap",m.number("snap-zero")?"Zero crossings":"Off");action("Detect transients","analysis.start","transients");}
  else {property("Value",history->text("value",history->text("detail")));property("State",history->number("on",1)?"On":"Bypassed");}
  if(!history->number("baseline")){ir("text","", "Operations are non-destructive; the source file is preserved.");action("Bypass","sample.history-bypass",history->id);action("Remove","sample.history-remove",history->id);}

 }else if(page=="empty"||m.records("source").empty()){
  heading("Instrument");property("Sounds",m.records("zone").empty()?"None":std::to_string(m.records("zone").size()));property("Voice limit",numberText(m.number("voice-limit")));property("Output","Main 1/2");ir("text","","Drop or browse a sample to create a sound.");
 }else if(page=="sample"&&selectedSource){
  inspectorTitle=selectedSource->text("name");inspectorType="Sample";inspectorIcon="level";heading("Sample");property("State",selectedSource->text("state"));property("Format",selectedSource->text("metadata"));property("Channels",std::to_string(static_cast<int>(selectedSource->number("channels"))));int count=0;for(auto& z:m.records("zone"))if(z.text("source")==selectedSource->id)++count;property("Used by",std::to_string(count)+" zone(s)");
  if(selectedSource->text("state")=="missing"||selectedSource->text("state")=="unsupported"){property("Last seen",selectedSource->text("path"));action("Locate file…","asset.relink",selectedSource->id);action("Search folder…","asset.search-folder",selectedSource->id);action("Replace with…","asset.replace",selectedSource->id);}
  else{heading("Region");property("Length",numberText(selectedSource->number("duration")*(m.number("region-end")-m.number("region-start"))),"s");property("Loop",m.number("loop-enabled")?numberText(m.number("loop-start"))+"–"+numberText(m.number("loop-end")):"Off");property("Root",numberText(m.number("root-note")));heading("Analysis");property("Pitch",m.text("analysis-root").empty()?"Not analysed":m.text("analysis-root"));property("Loudness",m.text("analysis-gain").empty()?"Not analysed":m.text("analysis-gain"),"dB");property("Zero crossings",selectedSource->text("zero-crossings").empty()?"Not analysed":"Ready");action("Replace…","asset.replace",selectedSource->id);}
 }else if(page=="mapping"||page=="layers"){
  auto zone=m.find("zone",m.text("selected-zone"));if(zone){inspectorTitle=zone->text("name");inspectorType=page=="mapping"?"Zone":m.text("selector-mode")=="round-robin"?"Alternate":"Layer";inspectorIcon=page=="mapping"?"keyboard":"layers";heading("Keys");property("Low",zone->text("lo"));property("High",zone->text("hi"));property("Root",zone->text("root-note"));heading("Velocity");property("Low",zone->text("vel-lo"));property("High",zone->text("vel-hi"));property("Crossfade",numberText(m.number("crossfade-width")));heading("Selection");property("Policy",m.text("selector-mode"));property("Weight",zone->text("weight","1"));property("Order",zone->text("order","0"));heading("Sample");auto asset=m.find("source",zone->text("source"));property("File",asset?asset->text("name"):zone->text("source"));action("Replace sample…","asset.replace",zone->text("source"));}
 }else if(page=="macros"){
  auto macro=m.find("macro",m.text("selected-macro"));if(macro){inspectorTitle=macro->text("name");inspectorType="Macro";inspectorIcon="variation";heading("Macro");property("Value",numberText(macro->number("value")*100),"%");property("MIDI",macro->text("midi-cc").empty()?"Unassigned":"CC "+macro->text("midi-cc"));property("Host automation",macro->number("host")?"On":"Off");action("Learn MIDI","macro.learn",macro->id);heading("Destinations");for(auto& binding:m.records("binding"))if(binding.text("macro")==macro->id){auto parameter=m.parameterInfo(binding.text("destination"));auto& row=ir("modulation",parameter?parameter->text("label"):binding.text("destination"),numberText(binding.number("minimum",0.2)*100)+"–"+numberText(binding.number("maximum",0.8)*100)+" %");row.fields["amount"]=binding.text("amount");row.fields["slot"]="4";row.fields["parameter-id"]=binding.text("destination");}action("Add destination…","inspector.macro-destinations",macro->id);}
 }else if(page=="mod"){
  auto modulator=m.text("selected-id")==m.text("selected-modulator")?m.find("modulator",m.text("selected-modulator")):nullptr;auto route=m.find("route",m.text("selected-route"));if(!modulator&&!route&&!m.records("route").empty())route=&m.records("route").front();
  if(modulator){inspectorTitle=modulator->text("name");inspectorType="Modulator";inspectorIcon="modulate";heading("Applied to");property("Scope",modulator->text("kind")=="lfo"?"Global":"Per voice");property("Kind",modulator->text("kind"));property("Shape",modulator->text("shape","ADSR"));heading("Routes");for(auto& r:m.records("route"))if(r.text("source")==modulator->id)routeRow(r);action("Apply to group…","route.add",modulator->id,"cutoff");}
  else if(route){auto source=m.find("modulator",route->text("source"));inspectorTitle=routeSourceName(*route)+" → "+routeDestinationName(*route);inspectorType="Route";inspectorIcon="modulate";heading("Route");routeRow(*route);property("Destination",routeDestinationName(*route));auto destination=m.parameterInfo(route->text("destination"));property("Base value",numberText(destination?destination->number("value"):0));property("Amount",route->text("amount"));property("Polarity",route->text("polarity","unipolar"));property("Curve",route->text("curve","linear"));property("Scope",route->text("scope","voice")=="shared"?"Shared":"Per voice");action("Edit source","modulator.select",route->text("source"));}
 }else if(page=="pads"||page=="diagnostics"){
  int note=static_cast<int>(m.number("selected-pad"));auto pad=m.find("pad",std::to_string(note));std::vector<const Record*> mapped;for(auto& z:m.records("zone"))if(note>=z.number("lo")&&note<=z.number("hi"))mapped.push_back(&z);inspectorTitle=mapped.empty()?"Empty pad":mapped.front()->text("name");inspectorType="Pad";heading("Pad");property("Note",std::to_string(note));property("Mapped sounds",std::to_string(mapped.size()));if(mapped.empty()){ir("text","","No rule maps this note, so it is silent.");action("Add zone…","zone.add",m.text("selected-source"),"",note);}else{property("Choke group",pad&&pad->number("choke",-1)>=0?pad->text("choke"):"None");property("Output",pad?pad->text("output","inherit"):"inherit");heading("Live");property("Pitch ratio",pad?pad->text("pitch-ratio","1"):"1","×");property("Level",pad?pad->text("gain","0"):"0","dB");property("Pan",pad?pad->text("pan","0"):"0");action("Open mapping","page.select","mapping");}
 }else if(page=="routing"){
  inspectorType=selected&&selected->text("kind")=="patch"?"Instrument":selected&&selected->text("kind")=="group"?"Group":"Sound";inspectorIcon="level";heading("Output");property("Bus",selected?selected->text("output","inherit"):"inherit");property("Inherited from",selected?selected->text("parent"):"patch");heading("Sends");for(auto name:{"Reverb","Delay"}){auto send=m.find("send",m.text("selected-id")+":"+name);property(name,send?send->text("value"):"0");}property("Send point","Post fader");
 }else if(page=="overview"){
  inspectorType=selected?selected->text("kind"):"Instrument";heading("Selection");property("Group",inspectorTitle);{auto parent=selected?m.find("tree",selected->text("parent")):nullptr;property("Inherits from",parent?parent->text("name"):"Instrument defaults");}ir("text","","Local rows override the parent; Reset restores inheritance.");
 }else if(page=="slices"){
  auto slice=m.find("slice",m.text("selected-slice"));inspectorTitle=slice?slice->text("name"):"Slices";inspectorType="Slice";inspectorIcon="slice";heading("Playback");property("Play",m.text("play-mode"));property("Tune",numberText(m.number("pitch")),"st");property("Gain",numberText(m.number("level")),"dB");property("Pan",numberText(m.number("pan")));heading("Region");property("Start",slice?slice->text("start"):"0");property("End",slice?slice->text("end"):"1");
 }else if(page=="voice"||page=="fx"){
  auto module=m.find(page=="fx"?"fx":"module",m.text("selected-id"));if(!module&&!m.records(page=="fx"?"fx":"module").empty())module=&m.records(page=="fx"?"fx":"module").front();inspectorType=page=="fx"?"Processor":"Module";inspectorIcon="settings";if(module){inspectorTitle=module->text("name");if(page=="fx"){ir("knobs","");inspectorParameters=m.processorParameters("fx",module->id);}heading("Module");property("Type",module->text("detail",module->text("name")));property("Bypass",module->number("bypassed")?"On":"Off");action("Bypass",page=="fx"?"fx.bypass":"module.bypass",module->id);heading("Modulation");for(auto& route:m.records("route"))routeRow(route);action("Assign modulation…","inspector.assign-modulation","cutoff");}
 }
 if(!inspectorType.empty())inspectorType[0]=static_cast<char>(std::toupper(static_cast<unsigned char>(inspectorType[0])));session_.set_inspector_title(str(inspectorTitle));session_.set_inspector_type(str(inspectorType));session_.set_inspector_icon(str(inspectorIcon));session_.set_inspector_crumbs(str(m.text("patch-name")+" / "+page+" / "+inspectorTitle));session_.set_inspector_has_history((page=="sample"||page=="slices")&&!m.records("source").empty());int overrideCount=0;for(auto& override:m.records("override"))if(override.text("parent")==m.text("selected-id")||override.id.starts_with(m.text("selected-id")+":"))++overrideCount;session_.set_inspector_override_count(overrideCount);
 session_.set_inspector_rows(project(session_.get_inspector_rows(),inspectorRows,[&](auto&x,auto&r){x.id=str(r.id);x.kind=str(r.text("kind"));x.label=str(r.text("label"));x.value=str(r.text("value"));x.unit=str(r.text("unit"));x.prepared=r.number("prepared");x.icon=str(r.text("icon"));x.primary=r.number("primary");x.action=str(r.text("action"));x.target=str(r.text("target"));x.field=str(r.text("field"));x.amount=r.number("amount");x.slot=r.number("slot");x.host=r.number("host");x.parameter_id=str(r.text("parameter-id"));}));
 session_.set_tree(project(session_.get_tree(),m.records("tree"),[&](auto& x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.parent=str(r.text("parent"));x.kind=str(r.text("kind"));x.detail=str(r.text("detail"));x.output=str(r.text("output","inherit"));x.resolved_output=str(m.outputFor(r.id));x.depth=r.number("depth");x.selected=r.id==m.text("selected-id");x.expanded=r.number("expanded",1);x.visible=true;std::string ancestor=r.text("parent");std::set<std::string> visited;while(!ancestor.empty()&&visited.insert(ancestor).second){auto p=m.find("tree",ancestor);if(!p)break;if(!p->number("expanded",1))x.visible=false;ancestor=p->text("parent");}x.muted=r.number("muted");x.solo=r.number("solo");x.frozen=r.number("frozen");}));
 std::vector<Record> overviewRows;
 auto overviewRow=[&](std::string id,std::string group,std::string label,std::string unit={}){overviewRows.push_back(Record{std::move(id),{{"group",std::move(group)},{"label",std::move(label)},{"unit",std::move(unit)}}});};
 for(auto group:{std::string("Output"),std::string("Audio source"),std::string("Voice"),std::string("Articulation")}){overviewRows.push_back(Record{"heading:"+group,{{"group",group},{"label",group},{"head","1"}}});if(group=="Output"){overviewRow("output",group,"Output bus");overviewRow("voice-limit",group,"Voice limit");overviewRow("voice-steal",group,"Steal");overviewRow("choke-group",group,"Choke group");}else if(group=="Audio source"){overviewRow("source-type",group,"Source type");overviewRow("fade-in",group,"Fade in","%");overviewRow("fade-out",group,"Fade out","%");}else if(group=="Voice"){overviewRow("cutoff",group,"Filter cutoff","Hz");overviewRow("amp-envelope",group,"Amp envelope");overviewRow("pitch",group,"Pitch","st");}else{overviewRow("articulation",group,"Articulation");overviewRow("release-sample",group,"Release sample");overviewRow("take-lock",group,"Take lock");}}
 session_.set_overview(project(session_.get_overview(),overviewRows,[&](auto&x,auto&r){x.id=str(r.id);x.group=str(r.text("group"));x.label=str(r.text("label"));x.unit=str(r.text("unit"));x.head=r.number("head");x.value=m.effective(m.text("selected-id"),r.id);std::string node=m.text("selected-id"),owner="patch";std::set<std::string> seen;bool overridden=false;while(!node.empty()&&seen.insert(node).second){if(m.find("override",node+":"+r.id)){owner=node;overridden=true;break;}auto t=m.find("tree",node);node=t?t->text("parent"):"";}x.owner=str(owner);auto tree=m.find("tree",owner);x.from=str(tree?tree->text("name"):"Instrument defaults");x.state=str(overridden?(owner==m.text("selected-id")?"local":"inherited"):"inherited");x.can_reset=overridden&&owner==m.text("selected-id");x.reset_action=str("inherit.reset");x.reset_target=str(m.text("selected-id"));x.reset_field=str(r.id);std::ostringstream value;value<<x.value;if(r.id=="output"){std::string output=selected?selected->text("output","inherit"):"inherit";x.value_text=str(output=="inherit"?"Main 1/2":output);x.can_reset=output!="inherit";x.state=str(x.can_reset?"local":"inherited");x.reset_action=str("routing.inherit");}else if(r.id=="voice-steal")x.value_text=str(m.text("voice-steal"));else if(r.id=="source-type")x.value_text=str(selectedSource?selectedSource->text("kind","Sampler"):"Sampler");else if(r.id=="amp-envelope")x.value_text=str(overridden?"Detached":"Default");else if(r.id=="articulation")x.value_text=str("Main hit");else if(r.id=="release-sample")x.value_text=str(x.value?"Yes":"No");else if(r.id=="take-lock")x.value_text=str(x.value?"On":"Off");else if(r.id=="choke-group")x.value_text=str(x.value?value.str():"None");else x.value_text=str(value.str()+(r.text("unit").empty()?"":" "+r.text("unit")));}));
 session_.set_resolved_output(str(m.outputFor(m.text("selected-id"))));session_.set_selected_output(str(selected?selected->text("output","inherit"):"inherit"));
 std::vector<Record> sends;for(auto name:{std::string("Reverb"),std::string("Delay"),std::string("Parallel")}){auto id=m.text("selected-id")+":"+name;auto existing=m.find("send",id);sends.push_back(existing?*existing:Record{id,{{"parent",m.text("selected-id")},{"name",name},{"value","0"}}});}session_.set_sends(project(session_.get_sends(),sends,[](auto&x,auto&r){x.id=str(r.id);x.parent=str(r.text("parent"));x.name=str(r.text("name"));x.value=r.number("value");}));
 std::vector<Record> candidates;const auto* selectedZone=m.find("zone",m.text("selected-zone"));
 for(auto& row:m.records("zone"))if(!selectedZone||(row.text("group")==selectedZone->text("group")&&row.number("lo")<=selectedZone->number("root-note")&&row.number("hi")>=selectedZone->number("root-note")&&(m.text("selector-mode")=="velocity"||m.text("selector-mode")=="stack"||(row.number("vel-lo",1)==selectedZone->number("vel-lo",1)&&row.number("vel-hi",127)==selectedZone->number("vel-hi",127))))){if((m.text("selector-mode")=="velocity"||m.text("selector-mode")=="stack")&&row.number("mapping-hidden"))continue;Record candidate=row;if(candidate.fields.contains("mapping-name")&&(m.text("selector-mode")=="velocity"||m.text("selector-mode")=="stack"))candidate.fields["name"]="Hard";candidates.push_back(candidate);}
 session_.set_candidates(project(session_.get_candidates(),candidates,[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.source=str(r.text("source"));x.output=str(r.text("output","inherit"));x.order=r.number("order");x.weight=r.number("weight",1);x.level=r.number("level",0.8);x.gain=r.number("gain");x.pan=r.number("pan");x.pitch=r.number("pitch");x.muted=r.number("muted");x.solo=r.number("solo");x.selected=r.id==m.text("selected-zone");x.vel_low=r.number("vel-lo",1);x.vel_high=r.number("vel-hi",127);}));
 auto fillSource=[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.path=str(r.text("path"));x.group=str(r.text("group","Samples"));x.favourite=r.number("favourite");x.kind=str(r.text("kind"));x.state=str(r.text("state"));x.metadata=str(r.text("metadata"));x.duration=r.number("duration");x.progress=r.number("progress");x.frames=r.number("frames");x.sample_rate=r.number("sample-rate");x.channels=r.number("channels");x.selected=r.id==m.text("selected-source");};
 session_.set_sources(project(session_.get_sources(),m.records("source"),fillSource));
 std::vector<Record> sourceGroups;std::set<std::string> sourceGroupNames;
 for(auto& source:m.records("source")){auto name=source.text("group","Samples");if(name.empty())name="Samples";if(sourceGroupNames.insert(name).second)sourceGroups.push_back(Record{name,{{"name",name}}});}
 session_.set_source_groups(project(session_.get_source_groups(),sourceGroups,[&](auto& x,auto& group){x.id=str(group.id);x.name=str(group.id);auto open=m.find("setting","source-open:"+group.id);x.expanded=open?open->number("value")!=0:group.id!="Break"&&group.id!="Keys"&&group.id!="Pad";decltype(x.sources) previous;auto oldGroups=session_.get_source_groups();if(oldGroups)for(std::size_t i=0;i<oldGroups->row_count();++i){auto old=oldGroups->row_data(i);if(old&&old->id==x.id){previous=old->sources;break;}}std::vector<Record> rows;for(auto& source:m.records("source")){auto name=source.text("group","Samples");if(name.empty())name="Samples";if(name==group.id)rows.push_back(source);}x.sources=project(previous,rows,fillSource);}));

 session_.set_render_progress(m.number("render-progress"));session_.set_freeze_mode(str(m.text("freeze-mode")));session_.set_freeze_tail(m.number("freeze-tail"));session_.set_voice_frozen((selectedSource&&selectedSource->number("frozen"))||(selected&&selected->number("frozen")));
 auto fillParameter=[&](auto&x,auto&r){x.id=str(r.id);x.label=str(r.text("label"));x.unit=str(r.text("unit"));x.group=str(r.text("group"));x.value=r.number("value");x.default_value=r.number("default");x.minimum=r.number("minimum");x.maximum=r.number("maximum");x.step=r.number("step");x.bipolar=x.minimum<0;x.host_automated=r.number("host");x.available=true;x.macro_bound=m.find("binding",m.text("selected-macro")+":"+r.id)!=nullptr;};
 session_.set_inspector_parameters(project(session_.get_inspector_parameters(),inspectorParameters,fillParameter));
 session_.set_autosampler_parameters(project(session_.get_autosampler_parameters(),m.autosamplerParameters(),fillParameter));
 session_.set_parameters(project(session_.get_parameters(),m.records("parameter"),fillParameter));
 // One bounded catalog exposes the same validated addresses accepted by commands.
 std::vector<Record> catalog;std::set<std::string> catalogIds;
 auto appendParameter=[&](std::string_view id,std::string_view ownerName={}){if(catalog.size()>=4096||catalogIds.contains(std::string(id)))return;if(auto descriptor=m.parameterInfo(id)){catalogIds.insert(descriptor->id);if(!ownerName.empty()){descriptor->fields["label"]=std::string(ownerName)+" · "+descriptor->text("label");descriptor->fields["group"]=std::string(ownerName);}catalog.push_back(std::move(*descriptor));}};
 for(auto& parameter:m.records("parameter"))appendParameter(parameter.id);
 for(auto table:{"module","fx"})for(auto& owner:m.records(table)){bool globalGroup=std::string_view(table)=="module"&&std::any_of(m.records("parameter").begin(),m.records("parameter").end(),[&](auto& p){return p.text("group")==owner.text("detail");});if(!globalGroup)for(auto& descriptor:m.processorParameters(table,owner.id))appendParameter(descriptor.id,owner.text("name"));}
 for(auto& modulator:m.records("modulator"))for(auto field:{"rate","depth","phase","attack","decay","sustain","release","smooth","fade-in","in-low","in-high"})appendParameter("modulator:"+modulator.id+":"+field);
 std::array<bool,128> mappedPads{};for(auto& zone:m.records("zone"))for(int note=std::max(0,static_cast<int>(zone.number("lo")));note<=std::min(127,static_cast<int>(zone.number("hi")));++note)mappedPads[note]=true;
 for(int note=0;note<128;++note)if(mappedPads[note])for(auto field:{"gain","pan","pitch-ratio","start","variation","send-a","send-b"})appendParameter("pad:"+std::to_string(note)+":"+field);
 session_.set_parameter_catalog(project(session_.get_parameter_catalog(),catalog,fillParameter));

 auto parameterGroup=[&](std::string_view group){std::vector<Record> rows;for(auto& row:m.records("parameter"))if(row.text("group")==group)rows.push_back(row);return rows;};
 session_.set_pitch_parameters(project(session_.get_pitch_parameters(),parameterGroup("Pitch"),fillParameter));
 session_.set_amp_parameters(project(session_.get_amp_parameters(),parameterGroup("Amplifier"),fillParameter));
 session_.set_filter_parameters(project(session_.get_filter_parameters(),parameterGroup("Filter"),fillParameter));
 session_.set_amp_envelope_parameters(project(session_.get_amp_envelope_parameters(),parameterGroup("Amp envelope"),fillParameter));
 session_.set_filter_envelope_parameters(project(session_.get_filter_envelope_parameters(),parameterGroup("Filter envelope"),fillParameter));
 session_.set_source_parameters(project(session_.get_source_parameters(),parameterGroup("Source"),fillParameter));

 std::vector<Record> mappingZones;int low=127,high=0,mappingLow=127,mappingHigh=0;for(const auto& z:m.records("zone")){low=std::min(low,static_cast<int>(z.number("lo")));high=std::max(high,static_cast<int>(z.number("hi")));bool scoped=!m.number("guide-fixture")||z.text("group")=="drums"||z.text("group")=="break";if(!z.number("mapping-hidden")&&scoped){mappingZones.push_back(z);mappingLow=std::min(mappingLow,static_cast<int>(z.number("lo")));mappingHigh=std::max(mappingHigh,static_cast<int>(z.number("hi")));}}session_.set_mapped_low(m.records("zone").empty()?24:low);session_.set_mapped_high(m.records("zone").empty()?31:high);session_.set_mapping_low(mappingZones.empty()?24:(mappingLow/12)*12);session_.set_mapping_high(mappingZones.empty()?47:std::min(127,std::max((mappingLow/12)*12+23,((mappingHigh/12)+1)*12-1)));
 session_.set_zones(project(session_.get_zones(),mappingZones,[](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("mapping-name",r.text("name")));x.source=str(r.text("source"));x.lo=r.number("lo");x.hi=r.number("hi");x.vel_lo=r.number("vel-lo",1);x.vel_hi=r.number("vel-hi",127);x.root_note=r.number("root-note");x.has_root=true;}));
 std::set<std::string> sourceIds;for(auto& source:m.records("source"))sourceIds.insert(source.id);std::vector<Record> sliceOwners;for(auto& slice:m.records("slice")){auto source=slice.text("source",m.text("selected-source"));sliceOwners.push_back(Record{slice.id,{{"source",sourceIds.contains(source)?source:""}}});}session_.set_slice_sources(project(session_.get_slice_sources(),sliceOwners,[](auto& x,auto& row){x.id=str(row.id);x.source=str(row.text("source"));}));
 auto sliceFill=[](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.start=r.number("start");x.end=r.number("end",1);};session_.set_slices(project(session_.get_slices(),m.records("slice"),sliceFill));session_.set_analysis_candidates(project(session_.get_analysis_candidates(),m.records("analysis"),sliceFill));
 std::vector<Row<decltype(session_.get_waveform())>> waveform;for(auto p:m.peaks()){Row<decltype(session_.get_waveform())> bucket{};bucket.minimum=p.minimum;bucket.maximum=p.maximum;waveform.push_back(bucket);}session_.set_waveform(std::make_shared<slint::VectorModel<Row<decltype(session_.get_waveform())>>>(std::move(waveform)));
 std::vector<Record> padRecords;auto held=m.heldNotes();for(int note=0;note<128;++note){std::vector<const Record*> zones;for(auto&z:m.records("zone"))if(note>=z.number("lo")&&note<=z.number("hi"))zones.push_back(&z);Record pad{std::to_string(note),{}};pad.fields["note"]=std::to_string(note);if(!zones.empty())pad.fields["name"]=zones.front()->text("name");pad.fields["mapped"]=zones.empty()?"0":"1";std::map<std::pair<int,int>,int> bands;int alternates=0;for(auto*z:zones)alternates=std::max(alternates,++bands[{static_cast<int>(z->number("vel-lo")),static_cast<int>(z->number("vel-hi"))}]);pad.fields["layers"]=std::to_string(bands.size());pad.fields["alternates"]=std::to_string(alternates>1?alternates:0);padRecords.push_back(pad);}
 session_.set_pads(project(session_.get_pads(),padRecords,[&](auto&x,auto&r){int note=r.number("note");x.id=str(r.id);x.name=str(r.text("name"));x.note=note;x.mapped=r.number("mapped");auto config=m.find("pad",r.id);x.pitch_ratio=config?config->number("pitch-ratio",1):1;x.gain=config?config->number("gain"):0;x.pan=config?config->number("pan"):0;x.start=config?config->number("start"):0;x.variation=config?config->number("variation"):0;x.muted=config&&config->number("muted");x.solo=config&&config->number("solo");x.output=str(config?config->text("output","inherit"):"inherit");x.send_a=config?config->number("send-a"):0;x.send_b=config?config->number("send-b"):0;x.choke_group=config?config->number("choke",-1):note==42||note==46?1:-1;x.selected=note==m.number("selected-pad");x.sounding=std::find(held.begin(),held.end(),note)!=held.end();auto live=m.find("pad-live",r.id);x.level=live?live->number("level"):0;x.velocity=live?live->number("velocity",100):100;x.active_alternate=live?static_cast<int>(live->number("alternate"))%std::max(1,static_cast<int>(r.number("alternates"))):0;x.choked=live&&live->number("choked");x.layers=r.number("layers");x.alternates=r.number("alternates");x.velocity_low=1;x.velocity_high=127;int key=note-static_cast<int>(m.number("octave-base"));x.key_label=str(m.number("pc-keys")&&key>=0&&key<13?std::string(1,"AWSEDFTGYHUJK"[key]):"");}));
 std::vector<Record> presets;std::string query=m.text("browser-query"),category=m.text("browser-category");std::transform(query.begin(),query.end(),query.begin(),[](unsigned char c){return std::tolower(c);});for(auto p:m.records("preset")){std::string hay=p.text("name")+" "+p.text("category")+" "+p.text("contents");std::transform(hay.begin(),hay.end(),hay.begin(),[](unsigned char c){return std::tolower(c);});bool cat=category.empty()||category=="All"||category=="all"||(category=="User"||category=="user"?p.text("origin")=="User":category=="Favourites"||category=="fav"?p.number("favourite")!=0:p.text("category")==category);if(cat&&(query.empty()||hay.find(query)!=std::string::npos))presets.push_back(p);}
 session_.set_presets(project(session_.get_presets(),presets,[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.category=str(r.text("category"));x.origin=str(r.text("origin"));x.contents=str(r.text("contents"));x.favourite=r.number("favourite");x.selected=r.id==(m.text("browser-selected").empty()?m.text("patch-id"):m.text("browser-selected"));}));
 session_.set_macros(project(session_.get_macros(),m.records("macro"),[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.value=r.number("value");x.default_value=r.number("default",0.5);x.minimum=r.number("minimum");x.maximum=r.number("maximum",1);x.unit=str(r.text("unit","%"));x.host_automated=r.number("host");x.destinations=strings(r.text("destinations"));std::vector<Row<decltype(x.assignments)>> assignments;for(auto&route:m.records("route"))if(route.text("destination")==r.id){Row<decltype(x.assignments)> a{};a.slot=route.number("slot");a.source=str(route.text("source"));a.depth=route.number("amount");a.active=route.number("on");assignments.push_back(a);}x.assignments=std::make_shared<slint::VectorModel<Row<decltype(x.assignments)>>>(std::move(assignments));}));
 std::vector<Record> macroBindings;for(auto& record:m.records("binding"))if(record.text("kind")!="midi")macroBindings.push_back(record);session_.set_macro_bindings(project(session_.get_macro_bindings(),macroBindings,[&](auto&x,auto&r){x.id=str(r.id);x.macro=str(r.text("macro"));x.destination=str(r.text("destination"));x.amount=r.number("amount");x.on=r.number("on",1);x.inverted=x.amount<0;auto p=m.parameterInfo(r.text("destination"));x.minimum=r.number("minimum",0.2);x.maximum=r.number("maximum",0.8);x.unit=str(p?p->text("unit"):"%");}));
 auto fillRoute=[&](auto&x,auto&r){x.id=str(r.id);x.source=str(r.text("source"));x.destination=str(r.text("destination"));x.source_name=str(routeSourceName(r));x.destination_name=str(routeDestinationName(r));x.scope=str(r.text("scope","voice"));x.combine=str(r.text("combine","add"));x.update_rate=str(r.text("rate","control"));x.polarity=str(r.text("polarity"));auto curve=r.text("curve");if(curve=="0"||curve=="1"||curve=="2"||curve=="3")curve=std::array<std::string,4>{"linear","exp","log","s-curve"}[static_cast<int>(r.number("curve"))];x.curve=str(curve);x.amount=r.number("amount");x.slot=r.number("slot");x.on=r.number("on",1);x.selected=r.id==m.text("selected-route");};
 session_.set_routes(project(session_.get_routes(),m.records("route"),fillRoute));
 std::string grouping=m.text("route-grouping")=="destination"?"destination":"source";session_.set_route_grouping(str(grouping));std::vector<Record> routeGroups;for(auto& route:m.records("route")){std::string key=route.text(grouping),id=grouping+":"+key;auto existing=std::find_if(routeGroups.begin(),routeGroups.end(),[&](auto& group){return group.id==id;});if(existing==routeGroups.end()){routeGroups.push_back(Record{id,{{"name",grouping=="source"?routeSourceName(route):routeDestinationName(route)},{"source",grouping=="source"?key:""},{"destination",grouping=="destination"?key:""}}});existing=routeGroups.end()-1;}auto label=grouping=="source"?routeDestinationName(route):routeSourceName(route);auto& summary=existing->fields["summary"];if(!summary.empty())summary+=" · ";std::ostringstream amount;amount<<std::lround(route.number("amount")*100);summary+=label+" "+amount.str()+"%";}
 session_.set_route_groups(project(session_.get_route_groups(),routeGroups,[&](auto& x,auto& group){x.id=str(group.id);x.name=str(group.text("name"));x.summary=str(group.text("summary"));x.source_id=str(group.text("source"));x.destination_id=str(group.text("destination"));x.expanded=m.text("route-open:"+group.id)!="0";decltype(x.routes) previous;auto groups=session_.get_route_groups();if(groups)for(std::size_t i=0;i<groups->row_count();++i){auto old=groups->row_data(i);if(old&&old->id==x.id){previous=old->routes;break;}}std::vector<Record> rows;for(auto route:m.records("route"))if(route.text(grouping)==(grouping=="source"?group.text("source"):group.text("destination")))rows.push_back(route);x.routes=project(previous,rows,fillRoute);}));

 session_.set_modulators(project(session_.get_modulators(),m.records("modulator"),[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.kind=str(r.text("kind"));x.shape=str(r.text("shape"));x.slot=r.number("slot");x.attack=r.number("attack",12);x.decay=r.number("decay",380);x.sustain=r.number("sustain",.3);x.release=r.number("release",1200);x.smooth=r.number("smooth");x.fade_in=r.number("fade-in");x.in_low=r.number("in-low");x.in_high=r.number("in-high",1);x.sync=r.number("sync");x.retrigger=r.number("retrigger",1);x.per_voice=r.number("per-voice",1);x.loop=r.number("loop");x.inverted=r.number("invert");x.rate=r.number("rate");x.depth=r.number("depth");x.phase=r.number("phase");x.live=r.number("live");x.enabled=r.number("enabled",1);x.selected=r.id==m.text("selected-modulator");}));
 std::vector<Record> modules=m.records("module");auto fx=m.records("fx");modules.insert(modules.end(),fx.begin(),fx.end());std::stable_sort(modules.begin(),modules.end(),[](auto&a,auto&b){return a.number("order")<b.number("order");});
 auto fillModule=[&](auto&x,auto&r){
  auto previous=session_.get_modules();decltype(x.parameters) oldParameters;
  if(previous)for(std::size_t i=0;i<previous->row_count();++i){auto row=previous->row_data(i);if(row&&row->id==str(r.id)){oldParameters=row->parameters;break;}}
  x.id=str(r.id);x.parent=str(r.text("parent"));x.name=str(r.text("name"));x.detail=str(r.text("detail"));std::string kind=r.text("detail",r.text("name"));std::transform(kind.begin(),kind.end(),kind.begin(),[](unsigned char c){return std::tolower(c);});kind=kind.find("noise")!=std::string::npos?"noise":kind.find("oscillator")!=std::string::npos?"oscillator":kind.find("sample")!=std::string::npos?"sampler":kind.find("synth")!=std::string::npos?"synth-patch":"processor";x.kind=str(kind);x.mode=str(r.text("mode",kind=="noise"?"white":kind=="oscillator"?"sine":kind=="sampler"?"once":"notes"));x.bypassed=r.number("bypassed");x.selected=r.id==m.text("selected-id");
  std::vector<Record> params;for(const auto& p:m.records("parameter"))if(p.text("group")==r.text("detail"))params.push_back(p);
  if(params.empty())params=m.processorParameters(m.find("fx",r.id)?"fx":"module",r.id);
  x.parameters=project(oldParameters,params,[](auto& v,const auto& p){v.id=str(p.id);v.label=str(p.text("label"));v.value=p.number("value");v.default_value=p.number("default");v.minimum=p.number("minimum");v.maximum=p.number("maximum",1);v.step=p.number("step");v.unit=str(p.text("unit"));v.bipolar=v.minimum<0;v.available=true;});
 };
 session_.set_modules(project(session_.get_modules(),modules,fillModule));
 session_.set_voice_modules(project(session_.get_voice_modules(),m.records("module"),fillModule));
 session_.set_effect_modules(project(session_.get_effect_modules(),m.records("fx"),fillModule));
 std::vector<Record> fxChains;for(auto& effect:m.records("fx")){std::string id=effect.text("parent");if(std::none_of(fxChains.begin(),fxChains.end(),[&](auto& c){return c.id==id;})){auto node=m.find("tree",id),bus=m.find("bus",id);fxChains.push_back(Record{id,{{"name",node?node->text("name"):bus?bus->text("name"):id},{"kind",bus?"bus":"group"}}});}}
 session_.set_fx_chains(project(session_.get_fx_chains(),fxChains,[&](auto& x,auto& chain){x.id=str(chain.id);x.name=str(chain.text("name"));x.kind=str(chain.text("kind"));decltype(x.processors) old;auto previous=session_.get_fx_chains();if(previous)for(std::size_t i=0;i<previous->row_count();++i){auto row=previous->row_data(i);if(row&&row->id==x.id){old=row->processors;break;}}std::vector<Record> processors;for(auto& effect:m.records("fx"))if(effect.text("parent")==chain.id)processors.push_back(effect);x.processors=project(old,processors,fillModule);}));


 session_.set_history(project(session_.get_history(),m.records("history"),[&](auto&x,auto&r){x.id=str(r.id);x.label=str(r.text("label"));x.detail=str(r.text("detail"));x.on=r.number("on",1);x.selected=r.id==m.text("selected-history");}));
 session_.set_diagnostics(project(session_.get_diagnostics(),m.records("diagnostic"),[](auto&x,auto&r){x.id=str(r.id);x.title=str(r.text("title"));x.detail=str(r.text("detail"));x.state=str(r.text("state"));}));std::vector<Record> hits;for(auto event:m.records("event"))if(event.text("kind")=="note-on")hits.push_back(event);session_.set_hits(project(session_.get_hits(),hits,[](auto&x,auto&r){x.sequence=std::stoi(r.id);x.kind=str(r.text("kind"));x.label=str(r.text("label"));}));session_.set_events(project(session_.get_events(),m.records("event"),[](auto&x,auto&r){x.sequence=std::stoi(r.id);x.kind=str(r.text("kind"));x.label=str(r.text("label"));}));session_.set_sounding_notes(std::make_shared<slint::VectorModel<int>>(held));session_.set_selected_zones(strings(m.text("selected-zone")));session_.set_selected_candidates(strings(m.text("selected-candidates")));
 session_.set_buses(project(session_.get_buses(),m.records("bus"),[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.channel_summary=str(r.text("channels"));x.main=r.number("main");x.feeds_known=true;std::string feeds;for(auto& node:m.records("tree"))if((node.text("kind")=="sound"||node.text("kind")=="synth")&&m.outputFor(node.id)==r.text("name")){if(!feeds.empty())feeds+=';';feeds+=node.text("name");}x.feeds=strings(feeds);std::vector<Row<decltype(x.channels)>> channels;for(int i=0;i<2;++i){Row<decltype(x.channels)> ch{};ch.id=str(r.id+":"+std::to_string(i));ch.name=str(i?"R":"L");ch.peak=m.number("output-level");ch.rms=ch.peak*0.7;ch.hold=ch.peak;ch.state=decltype(ch.state)::Valid;ch.ticket=str("silent-preview");channels.push_back(ch);}x.channels=std::make_shared<slint::VectorModel<Row<decltype(x.channels)>>>(std::move(channels));}));
 session_.set_layers(project(session_.get_layers(),m.records("zone"),[&](auto&x,auto&r){x.id=str(r.id);x.name=str(r.text("name"));x.source=str(r.text("source"));x.detail=str("velocity "+r.text("vel-lo")+"–"+r.text("vel-hi"));x.output=str("Main 1/2");x.level=r.number("level",0.8);x.muted=r.number("muted");x.can_level=true;x.can_mute=true;x.can_add=true;x.can_output=true;std::vector<Row<decltype(x.parameters)>> parameters;for(auto& id:{std::string("pitch"),std::string("fine"),std::string("cutoff"),std::string("pan"),std::string("level")}){auto p=m.find("parameter",id);if(!p)continue;Row<decltype(x.parameters)> v{};v.id=str(p->id);v.label=str(p->text("label"));v.value=p->number("value");v.default_value=p->number("default");v.minimum=p->number("minimum");v.maximum=p->number("maximum",1);v.step=p->number("step");v.unit=str(p->text("unit"));v.available=true;v.bipolar=v.minimum<0;parameters.push_back(v);}x.parameters=std::make_shared<slint::VectorModel<Row<decltype(x.parameters)>>>(std::move(parameters));x.waveform.supplied=!m.peaks().empty();x.waveform.label=str(r.text("name"));x.waveform.metadata=str("Silent mock source");x.waveform.state=str(m.text("asset-state"));x.waveform.peaks=session_.get_waveform();x.waveform.slices=session_.get_slices();x.waveform.selected_slice=str(m.text("selected-slice"));x.waveform.region_start=m.number("region-start");x.waveform.region_end=m.number("region-end");x.waveform.fade_in=m.number("fade-in");x.waveform.fade_out=m.number("fade-out");x.waveform.loop_enabled=m.number("loop-enabled");x.waveform.loop_start=m.number("loop-start");x.waveform.loop_end=m.number("loop-end");x.waveform.loop_crossfade=m.number("loop-crossfade");x.waveform.reversed=m.number("reversed");x.waveform.cursor=m.number("playhead");x.waveform.cursor_visible=x.waveform.cursor>0;x.waveform.spectral_state=str("unavailable");}));
 }
};
template<class Session> auto bindSession(const Session& session,std::shared_ptr<Model> model=std::make_shared<Model>()){return SessionBinding<Session>::create(session,std::move(model));}
// This convenience API retains the native window, making global lifetime explicit.
template<class Global,class Window> auto bindWindowSession(slint::ComponentHandle<Window> window,std::shared_ptr<Model> model=std::make_shared<Model>()){
 auto lifetime=std::make_shared<slint::ComponentHandle<Window>>(window);
 auto binding=bindSession(window->template global<Global>(),std::move(model));
 binding->retainWindow(std::move(lifetime));return binding;
}

}
