import {initialiseModule,setModuleValue} from '../voice-defaults.mjs';
import {clone,entity,named,finite,bounded,reorder} from '../validation.mjs';
export const instrumentOperations={
  setSelector(p,target,delta){const current=p.selectors[target];if(!current)throw new Error('Unknown selector');Object.assign(current,clone(delta));if(!['stack','velocity','rr','alt','random','weighted'].includes(current.policy))throw new Error('Invalid selector mode');},
  reorderCandidates(p,target,order){const selector=p.selectors[target];if(!selector)throw new Error('Unknown selector');selector.candidates=reorder(selector.candidates,order);},
  setCandidate(p,target,id,delta){const selector=p.selectors[target];if(!selector)throw new Error('Unknown selector');const candidate=entity(selector.candidates,id);Object.assign(candidate,clone(delta),{id});if(candidate.weight!=null&&finite(candidate.weight)<0)throw new Error('Negative weight');},
  setModuleParam(p,id,param,value){setModuleValue(p,entity(p.modules,id),param,value);},
  setVoicePolicy(p,delta){Object.assign(p.voicePolicy,clone(delta));if(!['poly','mono','legato'].includes(p.voicePolicy.mode)||!Number.isInteger(p.voicePolicy.limit)||p.voicePolicy.limit<1||p.voicePolicy.limit>128)throw new Error('Invalid voice policy');},
  setTemplate(p,modules){if(new Set(modules.map(m=>m.id)).size!==modules.length||!modules.length)throw new Error('Invalid voice template');p.modules=clone(modules);for(const module of p.modules)initialiseModule(p,module);},
  addRoute(p,route){const id=route.id??this.id('route');if(p.routes.some(r=>r.id===id))throw new Error('Duplicate route');entity(p.modulators,route.source);p.routes.push({...clone(route),id,amount:bounded(route.amount,-1,1),on:route.on??true});return id;},
  updateRoute(p,id,delta){const route=entity(p.routes,id);if(route.locked&&(delta.on===false||delta.source||delta.destination))throw new Error('Amp envelope route is fixed');Object.assign(route,clone(delta),{id});route.amount=bounded(route.amount,-1,1);},
  removeRoute(p,id){const route=entity(p.routes,id);if(route.locked)throw new Error('Amp envelope route is fixed');p.routes=p.routes.filter(r=>r.id!==id);},
  setModulator(p,id,delta){const mod=entity(p.modulators,id);if(mod.locked&&delta.kind)throw new Error('Amp envelope kind is fixed');Object.assign(mod,clone(delta),{id});},
  addModulator(p,kind){if(!['envelope','lfo','performance','macro','random'].includes(kind))throw new Error('Unknown modulator kind');const id=this.id('mod');p.modulators.push({id,name:kind==='lfo'?'LFO '+(p.modulators.filter(m=>m.kind===kind).length+1):'New '+kind,kind,slot:null,shape:kind==='lfo'?'sine':'adsr',config:{attack:.01,decay:.3,sustain:.5,release:1,rate:2}});return id;},
  removeModulator(p,id){const mod=entity(p.modulators,id);if(mod.locked)throw new Error('Amp envelope cannot be deleted');p.modulators=p.modulators.filter(m=>m.id!==id);p.routes=p.routes.filter(r=>r.source!==id);},
  setMacro(p,id,value){entity(p.macros,id).value=bounded(value,0,1);},
  renameMacro(p,id,name){entity(p.macros,id).name=named(name);},
  bindMacro(p,id,destination,range){const macro=entity(p.macros,id);if(range.length!==2||range.some(v=>!Number.isFinite(v)))throw new Error('Invalid macro range');const binding=macro.bindings.find(b=>b.destination===destination);if(binding)binding.range=clone(range);else macro.bindings.push({destination,range:clone(range)});},
  learnMidi(p,target){if(target===null){p.midiLearn=null;return;}if(!p.macros.some(m=>m.id===target)&&!p.params[target])throw new Error('Unknown MIDI target');p.midiLearn={target,state:'waiting'};},
  receiveMidi(p,cc,channel=1){if(!p.midiLearn)return;const target=p.macros.find(m=>m.id===p.midiLearn.target)??p.params[p.midiLearn.target];if(!target)throw new Error('Unknown MIDI target');target.midi={cc:bounded(cc,0,127),channel:bounded(channel,1,16)};p.midiLearn=null;},
  setOutput(p,node,bus){if(bus!=='inherit')entity(p.buses,bus);entity(p.nodes,node).output=bus;},
  setSend(p,node,fx,gain){if(!['rev','dly'].includes(fx))throw new Error('Unknown FX bus');const n=entity(p.nodes,node);n.sends={...n.sends,[fx]:bounded(gain,0,1)};},
  setBus(p,id,delta){Object.assign(entity(p.buses,id),clone(delta),{id});},
  addProcessor(p,chain,type,index){const c=entity(p.chains,chain),id=this.id('processor');const defaults={EQ:{Low:0,High:0},Compressor:{Threshold:-18,Ratio:4,Attack:10,Release:120,Makeup:0,Mix:100},Saturate:{Drive:0,Mix:100},Bitcrush:{Bits:12},Convolution:{Predelay:0,Mix:100},Delay:{Time:261,Feedback:35},Filter:{Cutoff:3200}};if(!defaults[type])throw new Error('Unknown processor');c.modules.splice(index??c.modules.length,0,{id,type,params:clone(defaults[type]),bypassed:false});return id;},
  moveProcessor(p,id,chain,index){const from=p.chains.find(c=>c.modules.some(m=>m.id===id));if(!from)throw new Error('Unknown processor');const to=entity(p.chains,chain),processor=entity(from.modules,id);from.modules=from.modules.filter(m=>m.id!==id);to.modules.splice(Math.max(0,Math.min(to.modules.length,index)),0,processor);},
  bypass(p,id,on){const module=p.chains.flatMap(c=>c.modules).find(m=>m.id===id)??p.modules.find(m=>m.id===id);if(!module)throw new Error('Unknown module');module.bypassed=!!on;},
  setProcessorParam(p,id,key,value){const processor=entity(p.chains.flatMap(c=>c.modules),id);processor.params[key]=finite(value);},
  removeProcessor(p,id){const chain=p.chains.find(c=>c.modules.some(m=>m.id===id));if(!chain)throw new Error('Unknown processor');chain.modules=chain.modules.filter(m=>m.id!==id);},
};
