#include "AdvancedSamplerBrowser.h"
#include "ui/advanced-sampler/engine/Bindings.h"
#include "ui/advanced-sampler/performance/Bindings.h"
#include "ui/slint/host/ValueCodec.h"
#include <slint-testing.h>
#include <slint-platform.h>
#include <cmath>
#include <iostream>
#include <stdexcept>

int main() {
    int checks = 0;
    const auto expect = [&](bool ok, const char* message) { ++checks; if (!ok) throw std::runtime_error(message); };
    try {
        slint::testing::init();
        auto window = dandrum_ui::AdvancedSamplerBrowserTest::create();
        auto model = std::make_shared<dandrum::sampler::Model>(); model->command("patch.load", "kit");
        auto binding = dandrum::sampler::bindWindowSession<dandrum_ui::Session>(window, model);
        dandrum::sampler::bind_patch_search(window->global<dandrum_ui::PatchFilter>());
        dandrum::slint_ui::bind_value_codec<dandrum_ui::ParsedValue>(window->global<dandrum_ui::ValueCodec>());
        window->show();
        const auto settle = [&] { slint::platform::update_timers_and_animations(); slint::invoke_from_event_loop([]{slint::quit_event_loop();}); slint::run_event_loop(); };
        const auto buttons = [&](const char* name) { settle(); std::vector<slint::testing::ElementHandle> found; for(auto row:slint::testing::ElementHandle::find_by_accessible_label(window,name)) if(row.accessible_role()==slint::language::AccessibleRole::Button&&row.size().height>0)found.push_back(row); return found; };
        const auto click = [&](const char* name) { auto found=buttons(name); expect(!found.empty(),name); found.front().invoke_accessible_default_action(); settle(); };
        model->selectState("loaded");binding->refresh();settle();
        expect(buttons("Back to instrument tree").size()==2,"Loaded guide state opens the instrument SourceBrowser operationally");
        click("Back to instrument tree");expect(buttons("Back to instrument tree").size()==1,"Manual browser close remains usable in the loaded state");
        model->selectState("sample");binding->refresh();settle();expect(buttons("Back to instrument tree").size()==1,"Ordinary guide state clears its browser projection");
        click("Sample browser");expect(buttons("Back to instrument tree").size()==2,"Manual browser open remains usable in ordinary states");
        model->selectState("voice");binding->refresh();settle();expect(buttons("Back to instrument tree").size()==1,"Switching guide state clears a previously manually opened browser");
        model->command("patch.load","kit");binding->refresh();settle();
        auto protectedMode=buttons("Protected mode Loop").front();auto initialMode=model->text("play-mode");
        protectedMode.invoke_accessible_default_action();settle();
        expect(protectedMode.accessible_enabled()==false&&model->text("play-mode")==initialMode,"Disabled segmented option cannot change a native setting");
        window->set_option_enabled(true);protectedMode.invoke_accessible_default_action();settle();
        expect(protectedMode.accessible_enabled()==true&&model->text("play-mode")=="loop","Reenabled segmented option can change its native setting");
        model->command("undo");binding->refresh();settle();
        window->invoke_set_query("KiCk"); settle();
        expect(model->text("source-query")=="KiCk","Sample query reaches canonical native state");
        expect(window->invoke_source_matches(0)&&!window->invoke_source_matches(1),"Case-insensitive source query preserves the matching browser row only");
        expect(!buttons("Preview Snare hard A.wav").empty(),"Browser filtering does not hide the instrument's source groups");
        window->invoke_set_query("no-such-asset"); settle();
        expect(!window->invoke_source_matches(0)&&!buttons("Preview Kick.wav").empty(),"Unmatched browser search preserves the source-group row");
        window->invoke_set_query(""); window->invoke_set_category("Drums"); settle();
        expect(model->text("source-category")=="Drums","Category reaches canonical native state");
        window->invoke_set_category("Samples");settle();
        expect(window->invoke_source_matches(0)&&window->invoke_source_matches(1),"Guide Samples category includes sampled assets across instrument groups");
        window->invoke_set_category("IRs");settle();
        expect(!window->invoke_source_matches(0),"Guide IR category excludes regular sampled assets");
        window->invoke_set_category("Favourites");settle();
        expect(!window->invoke_source_matches(0),"Guide Favourites category excludes an unmarked sampled asset");
        window->invoke_set_category("All");settle();
        click("Favourite Kick.wav");
        window->invoke_set_category("Favourites");settle();
        expect(window->invoke_source_matches(0)&&!window->invoke_source_matches(1),"Guide Favourites includes only native favourite sources");
        window->invoke_set_category("All");settle();
        click("Preview Kick.wav");
        expect(model->text("selected-source")=="kick-source"&&model->number("audition")==1&&model->heldNotes().empty(),"Source preview selects real cached source without note ownership");
        click("Select LFO 1 modulator");
        expect(model->text("selected-modulator")=="lfo1"&&model->text("page")=="mod","Modulator selection opens its actual native editor");
        auto routes=model->records("route").size(); auto undo=model->undoCount();
        expect(window->invoke_assign_modulator("lfo1","cutoff"),"Available parameter accepts a modulator assignment");
        expect(model->records("route").size()==routes+1&&model->undoCount()==undo+1,"Assignment creates one actual undoable route");
        expect(!window->invoke_assign_modulator("missing","cutoff")&&!window->invoke_assign_modulator("lfo1","missing"),"Invalid drag payloads cannot create routes");
        const auto center = [](const slint::testing::ElementHandle& element) { auto point=element.absolute_position(); auto size=element.size(); return slint::LogicalPosition{{point.x+size.width/2,point.y+size.height/2}}; };
        auto modulator=buttons("Select LFO 1 modulator").back();
        auto cutoff=slint::testing::ElementHandle::find_by_accessible_label(window,"Drop cutoff");
        expect(!cutoff.empty(),"Native drop target is an actual parameter control");
        auto from=center(modulator), to=center(cutoff[0]); routes=model->records("route").size();
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x+12,from.y}});
        window->window().dispatch_pointer_move_event(to);
        window->window().dispatch_pointer_release_event(to,slint::PointerEventButton::Left); settle();
        expect(model->records("route").size()==routes+1,"Native captured pointer drag creates a real modulation route on the destination control");
        expect(window->invoke_assign_source("kick","snare-source"),"Sound node accepts a loaded source");
        expect(model->find("zone","kick")->text("source")=="snare-source","Drop updates the real playable zone source");
        expect(model->command("undo"),"Source assignment is undoable"); binding->refresh();
        expect(model->find("zone","kick")->text("source")=="kick-source","Undo restores previous playable source");
        auto source=buttons("Preview Snare hard A.wav").back(); auto sound=buttons("Kick").front();
        from=center(sound);
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_pointer_release_event(from,slint::PointerEventButton::Left);settle();
        model->command("selection.set","snareS");binding->refresh();settle();
        window->window().dispatch_key_press_event(" ");window->window().dispatch_key_release_event(" ");settle();
        expect(model->text("selected-id")=="kick","Focused native instrument tree row supports Space selection");
        from=center(source); to=center(sound);
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x+12,from.y}});
        window->window().dispatch_pointer_move_event(to);
        window->window().dispatch_pointer_release_event(to,slint::PointerEventButton::Left); settle();
        expect(model->find("zone","kick")->text("source")=="snare-source","Native source drag updates the playable tree node without audition or note ownership");
        const auto sliceLabel=std::string("Preview ")+model->records("slice").front().text("name")+" slice";
        click(sliceLabel.c_str());
        expect(model->text("selected-source")=="break-source"&&model->text("selected-slice")==model->records("slice").front().id&&model->heldNotes().empty(),"Actual source-list slice preview selects its own source and region without MIDI ownership");
        window->global<dandrum_ui::Session>().invoke_command("asset.preview","kick-source","",0);settle();
        auto slice=buttons(sliceLabel.c_str()).front();from=center(slice);to=center(sound);
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x+12,from.y}});
        window->window().dispatch_pointer_move_event(to);
        window->window().dispatch_pointer_release_event(to,slint::PointerEventButton::Left);settle();
        auto sliceRegion=model->records("slice").front();
        expect(model->find("zone","kick")->text("source")=="break-source"&&model->find("zone","kick")->number("region-start")==sliceRegion.number("start")&&model->find("zone","kick")->number("region-end")==sliceRegion.number("end"),"Actual source-list slice drag preserves its own asset and playable region after another source was previewed");
        const auto zones=model->records("zone").size();
        auto pad=buttons("Pad 80 G♯5, empty"); expect(!pad.empty(),"Unmapped app pad offers an actual source drop target");
        from=center(source); to=center(pad.front());
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x+12,from.y}});
        window->window().dispatch_pointer_move_event(to);
        window->window().dispatch_pointer_release_event(to,slint::PointerEventButton::Left);settle();
        expect(model->records("zone").size()==zones+1&&model->number("selected-pad")==80,"Native source drag onto an empty pad creates a playable native mapping");
        model->command("undo");binding->refresh();settle();expect(!buttons("Pad 80 G♯5, empty").empty(),"Undo returns dropped pad to its actual unmapped appearance");
        from=center(slice);to=center(buttons("Pad 80 G♯5, empty").front());
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x+12,from.y}});
        window->window().dispatch_pointer_move_event(to);
        window->window().dispatch_pointer_release_event(to,slint::PointerEventButton::Left);settle();
        auto mappedSlice=model->find("zone",model->text("selected-zone"));
        expect(mappedSlice&&mappedSlice->text("source")=="break-source"&&mappedSlice->number("region-end")==sliceRegion.number("end"),"Actual source-list slice drop onto an empty pad preserves the slice asset and region");
        model->command("undo");binding->refresh();settle();
        auto soundCount=model->records("tree").size();auto zoneCount=model->records("zone").size();
        click("Add selected browser source to instrument");
        expect(model->records("tree").size()==soundCount+1&&model->records("zone").size()==zoneCount+1,"Browser Add to instrument creates a native sound and playable mapping");
        model->command("undo");binding->refresh();settle();
        click("Add group");
        expect(model->find("tree",model->text("selected-id"))->text("kind")=="group","Add group creates a group rather than a sound");
        for(const auto& item:std::vector<std::pair<const char*,const char*>>{{"Drop cutoff","cutoff"},{"Cancel level","level"}}){
            auto controls=slint::testing::ElementHandle::find_by_accessible_label(window,item.first);slint::testing::ElementHandle control=controls[0];
            for(auto row:controls)if(row.accessible_role()==slint::language::AccessibleRole::Slider)control=row;
            auto original=model->find("parameter",item.second)->number("value");undo=model->undoCount();from=center(control);from.y+=5;
            window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
            window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x,from.y-30}});settle();
            expect(model->find("parameter",item.second)->number("value")>original,"Captured native drag updates the actual parameter before cancellation");
            window->window().dispatch_pointer_exit_event();settle();
            expect(std::abs(model->find("parameter",item.second)->number("value")-original)<0.001&&model->undoCount()==undo,"Pointer cancellation restores the actual starting value without a history entry");
            window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);
            window->window().dispatch_pointer_move_event(slint::LogicalPosition{{from.x,from.y-30}});settle();
            expect(model->find("parameter",item.second)->number("value")>original,"Native control has an actual active drag before it becomes disabled");
            window->set_controls_enabled(false);settle();
            expect(std::abs(model->find("parameter",item.second)->number("value")-original)<0.001&&model->undoCount()==undo,"Disabling a captured control restores its actual starting value without committing history");
            window->window().dispatch_pointer_exit_event();window->set_controls_enabled(true);settle();
        }
        from=center(buttons("Select LFO 1 modulator").back());
        window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);window->window().dispatch_pointer_release_event(from,slint::PointerEventButton::Left);settle();
        window->global<dandrum_ui::Session>().invoke_command("modulator.select","amp-env","",0);settle();
        window->window().dispatch_key_press_event(" ");window->window().dispatch_key_release_event(" ");settle();
        expect(model->text("selected-modulator")=="lfo1","Clicked modulator row receives native keyboard focus for Space selection");
        for(const auto* label:{"Pad 80 G♯5, empty","Key 36 C2","Preview Kick.wav",sliceLabel.c_str(),"Select LFO 1 modulator","Kick"}){
            window->window().dispatch_window_active_changed_event(true);
            from=center(buttons(label).front());
            window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);settle();
            if(std::string_view(label)!="Pad 80 G♯5, empty"&&std::string_view(label)!="Key 36 C2"){
                window->window().dispatch_pointer_release_event(from,slint::PointerEventButton::Left);settle();
            }
            window->global<dandrum_ui::Session>().invoke_command("pc.enabled","","",1);
            window->global<dandrum_ui::Session>().invoke_pc_key("a",true,false,false);
            window->global<dandrum_ui::DragState>().invoke_begin("source","kick-source",from.x,from.y);
            expect(!model->heldNotes().empty(),"Pad or key focus shares a live native PC source before window deactivation");
            window->window().dispatch_window_active_changed_event(false);settle();
            expect(model->heldNotes().empty()&&!window->global<dandrum_ui::DragState>().get_active(),"Window deactivation on a pad or key releases global native notes and cancels internal drags");
            window->window().dispatch_pointer_exit_event();settle();
        }
        window->window().dispatch_window_active_changed_event(true);
        auto search=slint::testing::ElementHandle::find_by_accessible_label(window,"Search samples");
        auto input=search[0];for(auto row:search)if(row.accessible_role()==slint::language::AccessibleRole::TextInput)input=row;
        from=center(input);window->window().dispatch_pointer_press_event(from,slint::PointerEventButton::Left);window->window().dispatch_pointer_release_event(from,slint::PointerEventButton::Left);
        window->window().dispatch_key_press_event("k");window->window().dispatch_key_release_event("k");window->window().dispatch_key_press_event("i");window->window().dispatch_key_release_event("i");settle();
        expect(model->text("source-query")=="ki","Native browser text input publishes its actual search query");
        window->invoke_set_query("");settle();
        expect(input.accessible_value()==slint::SharedString(""),"Canonical search reset also clears the actual previously edited native input");
        window->global<dandrum_ui::Session>().invoke_pc_key("a",true,false,false);window->global<dandrum_ui::DragState>().invoke_begin("source","kick-source",from.x,from.y);
        window->window().dispatch_window_active_changed_event(false);settle();
        expect(model->heldNotes().empty()&&!window->global<dandrum_ui::DragState>().get_active(),"Window deactivation while browser text is focused balances existing PC sources and cancels drags");
        window->window().dispatch_window_active_changed_event(true);
        model->command("patch.load","kit");binding->refresh();settle();
        const auto context=[&](const char* row,bool last=false){auto found=buttons(row);expect(!found.empty(),row);auto at=center(last?found.back():found.front());window->window().dispatch_pointer_press_event(at,slint::PointerEventButton::Right);window->window().dispatch_pointer_release_event(at,slint::PointerEventButton::Right);settle();};
        context("Kick");click("Open Kick");expect(model->text("selected-id")=="kick"&&model->text("selected-source")==model->find("zone","kick")->text("source"),"Actual tree context Open selects its mapped source");
        const auto noteEvents=[&]{std::vector<dandrum::sampler::Record> notes;for(auto& e:model->records("event"))if(e.text("kind")=="note-on"||e.text("kind")=="note-off")notes.push_back(e);return notes;};auto auditionEvents=noteEvents().size();context("Kick");click("Audition Kick");auto auditionNotes=noteEvents();expect(model->heldNotes().empty()&&auditionNotes.size()==auditionEvents+2&&auditionNotes[auditionEvents].text("kind")=="note-on"&&auditionNotes.back().text("kind")=="note-off"&&auditionNotes[auditionEvents].text("label").starts_with(std::to_string(static_cast<int>(model->find("zone","kick")->number("lo")))+" ")&&auditionNotes.back().text("label")==std::to_string(static_cast<int>(model->find("zone","kick")->number("lo")))+" source tree-preview","Actual tree context Audition balances a preview for its mapped note");
        context("Kick");click("Mute Kick");expect(model->find("tree","kick")->number("muted")==1,"Actual tree context menu mutes its native target");
        context("Kick");click("Unmute Kick");expect(model->find("tree","kick")->number("muted")==0,"Actual tree context menu restores mute state");
        context("Kick");click("Solo Kick");expect(model->find("tree","kick")->number("solo")==1,"Actual tree context menu solos its native target");
        context("Kick");click("Unsolo Kick");expect(model->find("tree","kick")->number("solo")==0,"Actual tree context menu restores solo state");
        auto treeCount=model->records("tree").size();context("Kick");click("Duplicate Kick");expect(model->records("tree").size()==treeCount+1,"Actual tree context duplicate creates a new native instrument item");
        model->command("undo");binding->refresh();settle();
        context("Kick");click("Freeze Kick");expect(model->text("freeze-state")=="running","Actual tree context freeze starts its native render job");
        model->tick(1);binding->refresh();settle();expect(model->find("tree","kick")->number("frozen")==1,"Native tree context freeze completion marks its target");
        context("Kick");click("Unfreeze Kick");expect(model->find("tree","kick")->number("frozen")==0,"Actual tree context unfreeze restores editable target");
        const auto focusText=[&](const char* label){auto inputs=slint::testing::ElementHandle::find_by_accessible_label(window,label);expect(!inputs.empty(),label);for(auto row:inputs)if(row.accessible_role()==slint::language::AccessibleRole::TextInput){auto at=center(row);window->window().dispatch_pointer_press_event(at,slint::PointerEventButton::Left);window->window().dispatch_pointer_release_event(at,slint::PointerEventButton::Left);settle();return;}throw std::runtime_error("Missing actual rename text input");};
        context("Kick");click("Rename Kick");focusText("Rename instrument Kick");
        window->window().dispatch_key_press_event("\x1b");window->window().dispatch_key_release_event("\x1b");settle();
        context("Kick");click("Delete Kick");expect(!model->find("tree","kick"),"Actual tree context delete removes its native target");model->command("undo");binding->refresh();settle();
        context("Select LFO 1 modulator",true);click("Edit LFO 1");expect(model->text("selected-modulator")=="lfo1"&&model->text("page")=="mod","Actual modulator context edit navigates to its native editor");
        context("Select LFO 1 modulator",true);click("Show routes for LFO 1");expect(model->text("selected-modulator")=="lfo1"&&model->text("page")=="mod","Actual modulator Show routes opens its native route workspace");

        context("Select LFO 1 modulator",true);click("Disable LFO 1");expect(model->find("modulator","lfo1")->number("enabled")==0,"Actual modulator context disable updates its native state");
        context("Select LFO 1 modulator",true);click("Enable LFO 1");expect(model->find("modulator","lfo1")->number("enabled")==1,"Actual modulator context enable restores its native state");
        context("Select LFO 1 modulator",true);click("Rename LFO 1");focusText("Rename modulator LFO 1");
        window->window().dispatch_key_press_event("\x1b");window->window().dispatch_key_release_event("\x1b");settle();
        context("Select LFO 1 modulator",true);click("Delete LFO 1");expect(!model->find("modulator","lfo1"),"Actual modulator context delete removes its native record");model->command("undo");binding->refresh();settle();
        context("Preview Kick.wav",true);click("Preview source Kick.wav");expect(model->text("selected-source")=="kick-source"&&model->number("audition")==1&&model->heldNotes().empty(),"Actual source context preview auditions its cached source without owning a MIDI note");
        context("Preview Kick.wav",true);click("Show Kick.wav in browser");expect(!buttons("Back to instrument tree").empty(),"Actual source context opens the instrument's browser");
        model->command("asset.select","snare-source");binding->refresh();settle();
        context("Preview Kick.wav",true);click("Replace source Kick.wav");expect(window->get_requested_file_action()==slint::SharedString("asset.replace")&&window->get_requested_file_source()==slint::SharedString("kick-source")&&model->text("selected-source")=="kick-source","Actual source Replace selects its own source before emitting the real file chooser request");
        context("Preview Kick.wav",true);click("Detect transients in Kick.wav");expect(model->text("analysis-state")=="running"&&model->text("page")=="slices"&&model->text("selected-source")=="kick-source","Actual source context opens Slices and starts native analysis for its source");model->command("analysis.cancel");binding->refresh();
        auto sourceZones=model->records("zone").size();context("Preview Kick.wav",true);click("Remove source Kick.wav from patch");expect(!model->find("source","kick-source")&&model->records("zone").size()<sourceZones,"Actual source Remove deletes its native asset and mapped references");model->command("undo");binding->refresh();settle();expect(model->find("source","kick-source")&&model->records("zone").size()==sourceZones,"Undo restores the source context removal and every mapped reference");
        auto destinationRoutes=model->records("route").size();context("Select LFO 1 modulator",true);click("Add destination to LFO 1");click("Route LFO 1 to Level");expect(model->records("route").size()==destinationRoutes+1&&model->records("route").back().text("source")=="lfo1"&&model->records("route").back().text("destination")=="level",(std::string("Actual modulator destination picker creates its native parameter route: before=")+std::to_string(destinationRoutes)+" after="+std::to_string(model->records("route").size())+" source="+model->records("route").back().text("source")+" destination="+model->records("route").back().text("destination")).c_str());
        auto typedRoutes=model->records("route").size();auto typedUndo=model->undoCount();
        context("Select LFO 1 modulator",true);click("Add destination to LFO 1");
        auto destinationScroll=center(buttons("Select LFO 1 modulator").back());destinationScroll.y+=70;
        for(int step=0;step<35&&buttons("Route LFO 1 to Pad 38 Pan").empty();++step){window->window().dispatch_pointer_scroll_event(destinationScroll,0,-240);slint::cbindgen_private::slint_mock_elapsed_time(250);settle();}
        click("Route LFO 1 to Pad 38 Pan");
        expect(model->records("route").size()==typedRoutes+1&&model->records("route").back().text("destination")=="pad:38:pan"&&model->undoCount()==typedUndo+1,"Actual modulator picker creates one undoable route to a native typed pad parameter");
        model->command("undo");binding->refresh();settle();expect(model->records("route").size()==typedRoutes,"Undo removes the actual typed modulator destination route");
        click("Back to instrument tree");
        auto patchName=model->find("tree","patch")->text("name");context(patchName.c_str());
        auto deletePatch=buttons(("Delete "+patchName).c_str());expect(!deletePatch.empty()&&deletePatch.front().accessible_enabled()==false,"Instrument root cannot be deleted through its actual context menu");
        deletePatch.front().invoke_accessible_default_action();settle();expect(model->find("tree","patch")&&model->records("zone").size()==sourceZones,"Disabled instrument Delete preserves the root and playable mapping");
        click(("Open "+patchName).c_str());
        auto envelopes=buttons("Toggle envelope modulators");envelopes.back().invoke_accessible_default_action();settle();context("Select Amp envelope modulator",true);
        auto deleteEnvelope=buttons("Delete Amp envelope");expect(!deleteEnvelope.empty()&&deleteEnvelope.front().accessible_enabled()==false,"Required amp envelope has a disabled actual Delete menu action");
        deleteEnvelope.front().invoke_accessible_default_action();settle();expect(model->find("modulator","amp-env"),"Disabled amp envelope Delete preserves its native modulator");
        click("Edit Amp envelope");
        model->command("patch.load","kit");binding->refresh();settle();
        window->invoke_set_category("Samples");
        expect(model->command("freeze.start","kick-source"),"Native source freeze starts for category membership test");model->tick(1);binding->refresh();settle();
        expect(model->find("source","kick-source")->text("kind")=="frozen"&&window->invoke_source_matches(0),"Samples category includes the actual native frozen sample source");
        model->command("sample.unfreeze","kick-source");
        model->command("autosampler.configure","","lo",36);model->command("autosampler.configure","","hi",36);model->command("autosampler.configure","","layers",1);model->command("autosampler.configure","","rr",1);
        expect(model->command("autosampler.start","kick-source"),"Native one-sample mock render starts for category membership test");model->tick(1);binding->refresh();settle();
        auto renderedIndex=model->records("source").size()-1;
        expect(model->records("source")[renderedIndex].text("kind")=="mock-render"&&window->invoke_source_matches(renderedIndex),"Samples category includes the actual native mock-render asset");
        model->command("patch.load","kit");binding->refresh();settle();
        const auto recordField=[&](const char* table,const char* id,const char* key,const char* value){auto document=model->definition();auto begin=document.find(std::string("record \"")+table+"\" \""+id+"\"");auto end=document.find("\nrecord ",begin);auto field=document.find(std::string("\"")+key+"\" \"",begin);expect(begin!=std::string::npos&&field!=std::string::npos&&(end==std::string::npos||field<end),"Category/group fixture changes an existing serialized record field");auto from=field+std::string(key).size()+4;auto to=document.find('"',from);document.replace(from,to-from,value);expect(model->importDefinition(document),"Category/group fixture imports its real native record");binding->refresh();settle();};
        const auto sourceField=[&](const char* id,const char* key,const char* value){recordField("source",id,key,value);};
        sourceField("kick-source","kind","ir");window->invoke_set_category("IRs");settle();
        expect(window->invoke_source_matches(0)&&!window->invoke_source_matches(1),"Positive IR category includes an existing typed IR record and excludes a normal sample");
        window->invoke_set_category("Samples");settle();expect(!window->invoke_source_matches(0)&&window->invoke_source_matches(1),"Samples category excludes an IR record without changing native source contents");
        model->command("patch.load","kit");binding->refresh();settle();
        sourceField("keys-source","group","Drums");
        expect(buttons("Toggle Drums sources").size()==2,"Each actual SourceGroups component renders one header for a noncontiguous native source group");
        expect(buttons("Preview Felt C4.wav").size()==3,"Noncontiguous grouped sample remains visible under its shared expanded group");
        model->command("patch.load","kit");binding->refresh();settle();
        sourceField("break-source","group","Rendered");sourceField("keys-source","group","Imports");
        auto importedRows=buttons("Preview Felt C4.wav").size();auto renderedRows=buttons("Preview Amen 172.wav").size();auto groupsUndo=model->undoCount();
        auto renderedHeaders=buttons("Toggle Rendered sources");expect(!renderedHeaders.empty(),"Actual custom source group header exists");renderedHeaders.back().invoke_accessible_default_action();settle();
        expect(buttons("Preview Amen 172.wav").size()<renderedRows&&buttons("Preview Felt C4.wav").size()==importedRows,"Collapsing a custom source group preserves another custom group's expanded rows");
        expect(model->undoCount()==groupsUndo,"Source group presentation collapse leaves native editing history unchanged");
        model->command("patch.load","kit");binding->refresh();settle();
        recordField("slice","sl0","source","keys-source");
        model->command("asset.select","kick-source");binding->refresh();settle();
        auto previewRows=buttons("Preview Slice 1 slice");auto previewRow=previewRows.front();
        for(auto row:previewRows)if(row.absolute_position().x>=570&&row.absolute_position().y==450)previewRow=row;
        previewRow.invoke_accessible_default_action();settle();
        expect(model->text("selected-source")=="keys-source"&&model->text("selected-slice")=="sl0"&&model->number("audition")==1&&model->number("playhead")==model->find("slice","sl0")->number("start")&&model->heldNotes().empty(),"Actual slice preview resolves persisted provenance despite a stale source-row property");
        model->command("asset.group-toggle","Break");binding->refresh();settle();
        expect(buttons("Preview Slice 1 slice").size()==1,"Break source rows exclude a slice owned by a different native source");
        click("Toggle Keys sources");
        expect(buttons("Preview Slice 1 slice").size()==2,"Expanding a slice's actual owner shows its row in the visible native source group");
        const auto groupedSliceY=[&]{std::string positions;for(auto row:buttons("Preview Slice 1 slice")){auto pos=row.absolute_position();positions+=" x="+std::to_string(pos.x)+" y="+std::to_string(pos.y);if(pos.x>250&&pos.x<570)return pos.y;}throw std::runtime_error("Missing actual grouped slice row:"+positions);};
        model->command("asset.preview","kick-source");binding->refresh();settle();expect(buttons("Preview Slice 1 slice").size()==2,"Previewing another source preserves grouped slice rows with their stored provenance");auto oldSliceY=groupedSliceY();
        recordField("slice","sl0","source","break-source");
        expect(buttons("Preview Slice 1 slice").size()==1,"Native definition import resets transient source-group expansion");
        click("Toggle Break sources");
        expect(groupedSliceY()<oldSliceY,"A provenance-only native import moves the existing slice row to its owning source group");
        std::cout<<"PASS: "<<checks<<" native source/browser/modulator checks\n";
        return 0;
    } catch(const std::exception& error) { std::cerr<<"FAIL: "<<error.what()<<'\n'; return 1; }
}
