#include "AdvancedSamplerDomainRender.h"
#include "ui/advanced-sampler/engine/Bindings.h"
#include "ui/slint/host/ValueCodec.h"
#include <slint-testing.h>
#include <chrono>
#include <cmath>
#include <fstream>
#include <iostream>
#include <stdexcept>
// Render the actual native Slint paths on the caller's private virtual display.
int main(int argc,char**argv){if(argc!=2)return 2;int checks=0;try{auto w=AdvancedSamplerDomainRender::create();auto b=dandrum::sampler::bindWindowSession<Session>(w);const auto&s=w->global<Session>();dandrum::slint_ui::bind_value_codec<ParsedValue>(w->global<ValueCodec>());s.invoke_command("patch.load","kit","",0);s.invoke_command("modulator.select","filter-env","",0);int phase=0;std::string failure;slint::Timer timer;
 auto require=[&](bool ok,std::string text){++checks;if(!ok)throw std::runtime_error(text);};
 timer.start(slint::TimerMode::Repeated,std::chrono::milliseconds(150),[&]{try{auto image=w->window().take_snapshot();require(image.has_value(),"Actual native renderer supplies snapshot");std::ofstream output(std::string(argv[1])+"/domain-"+std::to_string(phase)+".pam",std::ios::binary);output<<"P7\nWIDTH "<<image->width()<<"\nHEIGHT "<<image->height()<<"\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";output.write(reinterpret_cast<const char*>(image->begin()),image->width()*image->height()*4);std::string label=phase==0?"Modulator graph Filter envelope":phase==1?"Modulator graph LFO 1":"Processor graph Compressor";auto plots=slint::testing::ElementHandle::find_by_accessible_label(w,label);require(!plots.empty(),"Native graph exists: "+label);if(phase==1){auto rates=slint::testing::ElementHandle::find_by_accessible_label(w,"Rate"),depths=slint::testing::ElementHandle::find_by_accessible_label(w,"Depth");require(!rates.empty()&&!depths.empty(),"Actual LFO controls exist");require(rates[0].absolute_position().x+rates[0].size().width<=depths[0].absolute_position().x+1,"Visible LFO Rate and Depth controls do not overlap");}auto p=plots[0].absolute_position();auto size=plots[0].size();double tx=phase==0?.3:phase==1?.125:.85,ty=phase==0?.68:phase==1?.275:.2625;bool near=false;for(int dy=-2;dy<=2;++dy)for(int dx=-2;dx<=2;++dx){int x=std::lround(p.x+tx*size.width)+dx,y=std::lround(p.y+ty*size.height)+dy;if(x<0||y<0||x>=image->width()||y>=image->height())continue;auto pixel=image->begin()[y*image->width()+x];near=near||(phase<2?pixel.g>135&&pixel.b>135&&pixel.r<130:pixel.r>160&&pixel.g>130&&pixel.b<160);}require(near,"Native graph stroke passes known normalized point in phase "+std::to_string(phase));if(++phase==3){timer.stop();slint::quit_event_loop();}else if(phase==1)s.invoke_command("modulator.select","lfo1","",0);else{s.invoke_command("fx.add","drums","Compressor",0);w->set_page("fx");}}catch(const std::exception&e){failure=e.what();timer.stop();slint::quit_event_loop();}});w->run();if(!failure.empty())throw std::runtime_error(failure);require(phase==3,"Envelope/LFO/compressor actual renderer cases completed");std::cout<<"PASS: "<<checks<<" actual native domain renderer checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
