#include "ui/advanced-sampler/engine/Model.h"
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace dandrum::sampler;
#define REQUIRE(x) do { ++assertions; if (!(x)) throw std::runtime_error(std::string(__func__)+":"+std::to_string(__LINE__)+": " #x); } while(false)
static int assertions=0, groups=0;
static void ready(Model& m) { m.tick(2.0); }
static void history() {
 Model noOp;noOp.command("patch.load","kit");double displayed=static_cast<float>(noOp.number("amp-sustain"));REQUIRE(noOp.gesture("amp-sustain",0,displayed));REQUIRE(noOp.gesture("amp-sustain",2,displayed));REQUIRE(noOp.undoCount()==0);REQUIRE(noOp.number("amp-sustain")==.68);
 Model m; REQUIRE(m.text("patch-id")=="empty"); REQUIRE(m.command("patch.load","kit"));
 double v=m.number("cutoff"); REQUIRE(m.gesture("cutoff",0,v)); REQUIRE(m.gesture("cutoff",1,1000)); REQUIRE(m.gesture("cutoff",1,2000)); REQUIRE(m.gesture("cutoff",2,2000)); REQUIRE(m.undoCount()==1); REQUIRE(m.number("cutoff")==2000);
 REQUIRE(m.command("undo")); REQUIRE(m.number("cutoff")==v); REQUIRE(m.command("redo")); REQUIRE(m.number("cutoff")==2000);
 REQUIRE(m.gesture("cutoff",0,2000)); REQUIRE(m.gesture("cutoff",1,500)); REQUIRE(m.gesture("cutoff",3,500)); REQUIRE(m.number("cutoff")==2000); REQUIRE(m.undoCount()==1); REQUIRE(!m.command("invented-action")); ++groups;
}
static void patch() {
 Model m; REQUIRE(m.command("patch.load","keys")); REQUIRE(m.records("zone").size()==10); REQUIRE(m.command("tree.rename","keys","Edited Keys")); REQUIRE(m.find("tree","keys")->text("name")=="Edited Keys"); REQUIRE(m.command("tree.duplicate","keys")); REQUIRE(m.records("tree").size()>3); std::string d=m.definition(); Model n; REQUIRE(n.importDefinition(d)); REQUIRE(n.definition()==d); std::string saved=n.definition(); REQUIRE(!n.importDefinition("not a patch")); REQUIRE(n.definition()==saved); REQUIRE(m.command("patch.load","hybrid")); REQUIRE(m.records("module").size()>=4); REQUIRE(m.command("patch.favourite","kit")); REQUIRE(m.find("preset","kit")->number("favourite")==0); ++groups;
}
static std::filesystem::path wav() { auto p=std::filesystem::temp_directory_path()/"dandrum-model-test.wav"; std::ofstream f(p,std::ios::binary); auto u16=[&](unsigned x){f.put(x&255);f.put((x>>8)&255);};auto u32=[&](unsigned x){u16(x&65535);u16(x>>16);}; f.write("RIFF",4);u32(44);f.write("WAVEfmt ",8);u32(16);u16(1);u16(1);u32(4);u32(8);u16(2);u16(16);f.write("data",4);u32(8);u16(0);u16(16384);u16(32768);u16(32767);return p; }
static void assets() {
 Model m; auto p=wav(); REQUIRE(m.command("asset.import","",p.string())); REQUIRE(m.text("asset-state")=="loading"); ready(m); REQUIRE(m.text("asset-state")=="loaded"); auto a=m.records("source").front(); REQUIRE(a.number("frames")==4); REQUIRE(a.number("duration")==1); REQUIRE(m.peaks().size()==4); REQUIRE(std::abs(m.peaks()[1].maximum-0.5)<0.001); REQUIRE(m.peaks()[2].minimum==-1);
 REQUIRE(m.command("sample.set","region-start","",0.2)); REQUIRE(m.command("sample.set","region-end","",0.8)); REQUIRE(m.command("sample.set","loop-start","",0.3)); REQUIRE(m.command("sample.set","loop-end","",0.7)); REQUIRE(m.command("sample.set","fade-in","",0.1)); REQUIRE(m.command("sample.set","reversed","",1)); REQUIRE(m.number("region-start")==0.2); REQUIRE(m.records("history").size()>=6);
 auto h=m.records("history")[4].id; REQUIRE(m.command("sample.history-bypass",h)); REQUIRE(m.number("fade-in")==0); REQUIRE(m.command("sample.history-bypass",h)); REQUIRE(m.number("fade-in")==0.1);
 auto id=a.id; REQUIRE(m.command("asset.relink",id,p.string()+".missing"));ready(m); REQUIRE(m.text("asset-state")=="missing");REQUIRE(m.command("asset.relink",id,p.string()));ready(m);REQUIRE(m.text("asset-state")=="loaded");REQUIRE(m.command("sample.freeze",id));ready(m);REQUIRE(m.find("source",id)->number("frozen")==1); std::filesystem::remove(p); ++groups;
}
static void analysis() {
 Model m;m.command("patch.load","kit"); REQUIRE(m.command("analysis.start","transients"));REQUIRE(m.text("analysis-state")=="running");auto old=m.records("slice").size();ready(m); REQUIRE(m.text("analysis-state")=="done");REQUIRE(m.records("slice").size()==old);REQUIRE(m.records("analysis").size()>=2);auto expected=m.records("analysis").size();REQUIRE(m.command("analysis.apply"));REQUIRE(m.records("slice").size()==expected);REQUIRE(m.command("slice.split",m.records("slice")[0].id,"",0.05));REQUIRE(m.command("undo"));REQUIRE(m.command("analysis.start","pitch"));REQUIRE(m.command("analysis.cancel"));ready(m);REQUIRE(m.text("analysis-state")=="idle"); REQUIRE(m.command("analysis.fail","loops"));ready(m);REQUIRE(m.text("analysis-state")=="failed");REQUIRE(m.command("analysis.retry"));ready(m);REQUIRE(m.text("analysis-state")=="done");REQUIRE(m.command("analysis.discard"));REQUIRE(m.records("analysis").empty()); ++groups;
}
static void mapping() {
 Model next;next.command("patch.load","keys");next.command("zone.select","k48p");REQUIRE(next.command("zone.copy-range","k48p"));REQUIRE(next.command("zone.paste-layer","","",-1));auto pasted=next.find("zone",next.text("selected-zone"));REQUIRE(pasted&&pasted->number("lo")==54);REQUIRE(pasted->number("hi")==59);
 Model m;m.command("patch.load","keys"); REQUIRE(m.command("zone.set","k48p","hi",55));REQUIRE(m.find("zone","k48p")->number("hi")==55);REQUIRE(m.find("zone","k55p")->number("lo")==56);REQUIRE(m.command("undo"));REQUIRE(m.find("zone","k55p")->number("lo")==54);REQUIRE(m.command("zone.move","k48p","",-100));REQUIRE(m.find("zone","k48p")->number("lo")>=0);REQUIRE(m.command("zone.copy","k60p"));auto count=m.records("zone").size();REQUIRE(m.command("zone.paste-layer","","",90));REQUIRE(m.records("zone").size()==count+1);
 for(auto mode:{"stack","velocity","round-robin","alternate","random","weighted"}) { REQUIRE(m.command("selector.mode","",mode)); REQUIRE(m.text("selector-mode")==mode);auto chosen=m.selectCandidates(60,100); REQUIRE(!chosen.empty()); }
 REQUIRE(m.command("layer.set","k60f","weight",0.8));REQUIRE(m.find("zone","k60f")->number("weight")==0.8);REQUIRE(m.command("selector.crossfade","","equal-power",12));REQUIRE(m.number("crossfade-width")==12);++groups;
}
static void processing() {
 Model generic;generic.command("patch.load","kit");REQUIRE(generic.command("module.add","voice","Utility"));REQUIRE(generic.processorParameters("module",generic.records("module").back().id).size()==3);
 Model controls;controls.command("patch.load","kit");for(auto id:{"pitch-key-track","bend","filter-key-track","filter-env-amount","source-gain"})REQUIRE(controls.find("parameter",id));REQUIRE(controls.command("filter.mode","","hp"));REQUIRE(controls.text("filter-mode")=="hp");REQUIRE(controls.command("undo"));REQUIRE(controls.text("filter-mode")=="lp");REQUIRE(!controls.command("filter.mode","","invalid"));
 Model m;m.command("patch.load","kit");REQUIRE(m.command("parameter.set","cutoff","",2000)); REQUIRE(m.number("cutoff")==2000); REQUIRE(m.command("voice.policy","","mono"));REQUIRE(m.text("voice-policy")=="mono"); REQUIRE(m.command("module.add","voice","Waveshaper"));auto id=m.records("module").back().id; REQUIRE(m.processorParameters("module",id).size()==2);REQUIRE(m.command("module.bypass",id));REQUIRE(m.find("module",id)->number("bypassed")==1);REQUIRE(m.command("modulator.add","","LFO"));id=m.records("modulator").back().id;REQUIRE(m.command("modulator.set",id,"rate",4));REQUIRE(m.find("modulator",id)->number("rate")==4); REQUIRE(m.command("route.add",id,"cutoff",0.25));id=m.records("route").back().id;REQUIRE(m.command("route.set",id,"curve",2));REQUIRE(m.find("route",id)->number("curve")==2);REQUIRE(m.command("route.invert",id));REQUIRE(m.find("route",id)->number("amount")==-0.25);
 REQUIRE(m.command("macro.bind","tone","cutoff",0.5));REQUIRE(m.command("macro.set","tone","",0.8));REQUIRE(m.find("macro","tone")->number("value")==0.8);REQUIRE(m.command("macro.host","tone","",1));REQUIRE(m.find("macro","tone")->number("host")==1);REQUIRE(m.command("routing.output","kick","Drums 3/4"));REQUIRE(m.find("tree","kick")->text("output")=="Drums 3/4");REQUIRE(m.command("send.set","kick","Reverb",0.6));REQUIRE(m.find("send","kick:Reverb")->number("value")==0.6); REQUIRE(m.command("fx.add","main","Reverb"));id=m.records("fx").back().id;REQUIRE(m.command("fx.bypass",id));REQUIRE(m.find("fx",id)->number("bypassed")==1);REQUIRE(m.command("inherit.override","kick","pan",0.25));REQUIRE(m.effective("kick","pan")==0.25);REQUIRE(m.command("inherit.reset","kick","pan"));REQUIRE(m.effective("kick","pan")==0);++groups;
}
static void lifecycle() {
 Model m;m.command("patch.load","kit");REQUIRE(m.noteOn(38,120,"pad"));REQUIRE(m.noteOn(38,100,"keys"));REQUIRE(m.heldNotes().size()==1);m.noteOff(38,"pad");REQUIRE(m.heldNotes().size()==1);m.noteOff(38,"keys");REQUIRE(m.heldNotes().empty());m.command("pc.enabled","","",1);REQUIRE(!m.pcKey("a",true,true,false));REQUIRE(m.pcKey("a",true,false,false));REQUIRE(m.pcKey("a",true,false,false));REQUIRE(m.heldNotes().size()==1);m.command("pc.octave","","",12);REQUIRE(!m.pcKey("a",false,true,true));REQUIRE(m.heldNotes().empty()); REQUIRE(m.noteOn(127,100,"unmapped"));REQUIRE(m.records("diagnostic").back().text("detail").find("Silent")!=std::string::npos);m.releaseNotes();REQUIRE(m.heldNotes().empty()); for(int i=0;i<200;++i) m.noteOn(38,100,"repeat"); REQUIRE(m.records("event").size()<=128);m.command("patch.load","empty");REQUIRE(m.heldNotes().empty());++groups;
}
static void domainGestureAndDiagnostics() {
 Model m;m.command("patch.load","keys");auto count=m.undoCount();REQUIRE(m.gesture("zone:k60p:lo",0,60));REQUIRE(m.gesture("zone:k60p:lo",1,61));REQUIRE(m.gesture("zone:k60p:lo",2,61));REQUIRE(m.undoCount()==count+1);REQUIRE(m.find("zone","k60p")->number("lo")==61);REQUIRE(m.command("undo"));REQUIRE(m.find("zone","k60p")->number("lo")==60);
 m.noteOn(60,100,"test");std::string sequence=m.records("event").back().id;m.noteOff(60,"test");m.noteOn(127,100,"test");m.noteOff(127,"test");auto notes=m.records("event").size();REQUIRE(m.command("diagnostics.select",sequence));REQUIRE(m.records("diagnostic").front().text("detail").find("Note 60")!=std::string::npos);REQUIRE(m.records("event").size()==notes);REQUIRE(m.command("event.clear"));REQUIRE(m.records("diagnostic").empty());
 m.command("telemetry.fail","","",1);m.command("analysis.start","pitch");ready(m);REQUIRE(m.text("analysis-state")=="failed");++groups;
}
static void newGestureContracts() {
 Model m;m.command("patch.load","kit");auto initial=m.number("region-start");auto count=m.undoCount();REQUIRE(m.gesture("region-start",0,initial));REQUIRE(m.gesture("region-start",1,0.1));REQUIRE(m.gesture("region-start",1,0.15));REQUIRE(m.gesture("region-start",2,0.15));REQUIRE(m.undoCount()==count+1);REQUIRE(m.number("region-start")==0.15);REQUIRE(m.records("history").size()==1);REQUIRE(m.command("undo"));REQUIRE(m.number("region-start")==initial);REQUIRE(m.records("history").empty());
 REQUIRE(m.command("pad.select","","",38));REQUIRE(m.number("selected-pad")==38);REQUIRE(m.gesture("pad:38:pan",0,0));REQUIRE(m.gesture("pad:38:pan",1,0.5));REQUIRE(m.gesture("pad:38:pan",2,0.5));REQUIRE(m.find("pad","38")->number("pan")==0.5);REQUIRE(m.command("undo"));REQUIRE(!m.find("pad","38"));REQUIRE(m.command("pad.set","38","gain",-12));REQUIRE(m.find("pad","38")->number("gain")==-12);REQUIRE(m.command("pad.output","38","Snare 5/6"));REQUIRE(m.find("pad","38")->text("output")=="Snare 5/6");
 REQUIRE(m.gesture("binding:tone:cutoff",0,0.5));REQUIRE(m.gesture("binding:tone:cutoff",1,-0.6));REQUIRE(m.gesture("binding:tone:cutoff",3,-0.6));REQUIRE(m.find("binding","tone:cutoff")->number("amount")==0.5);REQUIRE(m.command("macro.binding-set","tone","cutoff",0.25));REQUIRE(m.find("binding","tone:cutoff")->number("amount")==0.25);m.command("pc.enabled","","",1);m.pcKey("a",true,false,false);m.command("pc.octave","","",12);REQUIRE(m.heldNotes().empty());++groups;
}
static void edgeCases() {
 Model m;m.command("patch.load","kit");auto generation=m.generation();REQUIRE(m.receive({generation,"ready","Accepted"}));m.command("patch.load","keys");REQUIRE(!m.receive({generation,"analysis","Must not apply"}));
 REQUIRE(m.command("selector.mode","","random"));std::string last;for(int i=0;i<30;++i){auto selected=m.selectCandidates(60,85);REQUIRE(selected.size()==1);REQUIRE(selected.front()!=last);last=selected.front();}
 REQUIRE(m.command("layer.set","k60f","weight",2));REQUIRE(m.find("zone","k60f")->number("weight")==2);REQUIRE(m.command("selector.mode","","weighted"));REQUIRE(m.command("layer.set","k60p","weight",0));for(int i=0;i<20;++i)REQUIRE(m.selectCandidates(60,85).front()=="k60f");
 REQUIRE(m.command("module.add","voice","Delay"));auto module=m.records("module").back().id; REQUIRE(m.command("module.move",module,"",-100)); REQUIRE(m.records("module").front().id==module);
 REQUIRE(m.command("tree.add","keys","Subgroup",1));auto node=m.text("selected-id");REQUIRE(!m.command("tree.move","keys",node));REQUIRE(m.command("tree.delete",node));REQUIRE(m.command("undo"));REQUIRE(m.find("tree",node));
 REQUIRE(m.command("macro.binding-set","tone:cutoff","minimum",0.2));REQUIRE(m.find("binding","tone:cutoff")->number("minimum")==0.2);REQUIRE(m.command("undo"));REQUIRE(m.find("binding","tone:cutoff")->text("minimum").empty());REQUIRE(m.command("pad.select","","",38));REQUIRE(m.number("selected-pad")==38);REQUIRE(m.text("selected-zone").empty());
 REQUIRE(m.command("macro.select","space"));REQUIRE(m.text("selected-macro")=="space");REQUIRE(m.command("macro.learn","tone"));REQUIRE(m.command("midi.receive","","",74));REQUIRE(m.find("macro","tone")->number("midi-cc")==74);
 auto before=m.number("level");REQUIRE(m.command("analysis.start","loudness"));ready(m);REQUIRE(m.command("analysis.apply"));REQUIRE(m.number("level")==-3);REQUIRE(m.command("undo"));REQUIRE(m.number("level")==before);++groups;
}
static void sourceBrowserAndAssignment() {
 Model m;auto p=wav();REQUIRE(m.command("asset.import","",p.string()));ready(m);
 auto source=m.text("selected-source");REQUIRE(m.text("page")=="sample");REQUIRE(m.records("zone").size()==1);REQUIRE(m.records("tree").size()==2);
 REQUIRE(m.command("asset.preview",source));REQUIRE(m.number("audition")==1);REQUIRE(m.command("sample.stop"));
 REQUIRE(m.command("asset.search","","felt"));REQUIRE(m.text("source-query")=="felt");REQUIRE(m.command("asset.category","","Keys"));REQUIRE(m.text("source-category")=="Keys");
 REQUIRE(m.command("tree.assign","patch",source));auto assigned=m.text("selected-id");REQUIRE(m.find("tree",assigned)->text("source")==source);auto zones=m.records("zone").size();REQUIRE(m.command("undo"));REQUIRE(!m.find("tree",assigned));REQUIRE(m.records("zone").size()==zones-1);
 m.command("patch.load","kit");REQUIRE(m.command("modulator.select","lfo1"));REQUIRE(m.text("selected-modulator")=="lfo1");REQUIRE(m.text("page")=="mod");
 REQUIRE(m.command("selection.set","snareS"));REQUIRE(m.text("selected-zone")=="snS");REQUIRE(m.text("selected-source")=="snare-source");REQUIRE(m.command("selection.set","snareH"));REQUIRE(m.text("selected-zone")=="snH");REQUIRE(m.text("selected-source")=="snare-source");
 REQUIRE(m.command("asset.favourite","snare-source"));REQUIRE(m.find("source","snare-source")->number("favourite")==1);REQUIRE(m.command("undo"));REQUIRE(m.find("source","snare-source")->number("favourite")==0);
 REQUIRE(m.command("asset.mock-state","kick-source","missing"));REQUIRE(m.find("source","kick-source")->text("state")=="missing");REQUIRE(!m.command("asset.preview","kick-source"));REQUIRE(m.command("asset.mock-state","kick-source","loaded"));REQUIRE(m.command("undo"));REQUIRE(m.find("source","kick-source")->text("state")=="missing");REQUIRE(!m.command("asset.mock-state","kick-source","invented"));REQUIRE(m.command("undo"));REQUIRE(m.command("automation.mock","","",1));REQUIRE(m.number("host-automation")==1);REQUIRE(m.command("automation.mock","","",0));REQUIRE(m.number("host-automation")==0);
 REQUIRE(m.command("tree.assign","kick","keys-source"));REQUIRE(m.find("tree","kick")->text("source")=="keys-source");REQUIRE(m.find("zone","kick")->text("source")=="keys-source");REQUIRE(m.command("undo"));REQUIRE(m.find("zone","kick")->text("source")=="kick-source");
 REQUIRE(m.command("asset.preview","kick-source"));m.command("sample.stop");REQUIRE(m.command("asset.relink","kick-source",p.string()+".missing"));ready(m);REQUIRE(!m.command("asset.preview","kick-source"));REQUIRE(m.number("audition")==0);REQUIRE(!m.command("tree.assign","lfo1","keys-source"));std::filesystem::remove(p);++groups;
}
static void typedProcessors(){
 Model m;m.command("patch.load","kit");REQUIRE(m.command("fx.add","drums","Compressor"));auto id=m.records("fx").back().id;auto parameters=m.processorParameters("fx",id);REQUIRE(parameters.size()==6);REQUIRE(parameters[0].text("label")=="Threshold");REQUIRE(parameters[0].number("value")==-18);REQUIRE(parameters[1].number("value")==4);REQUIRE(m.command("fx.set",id,"threshold",-999));REQUIRE(m.find("fx",id)->number("threshold")==-60);REQUIRE(m.command("undo"));auto n=m.undoCount();REQUIRE(m.gesture("fx:"+id+":threshold",0,-18));REQUIRE(m.gesture("fx:"+id+":threshold",1,-24));REQUIRE(m.gesture("fx:"+id+":threshold",2,-24));REQUIRE(m.undoCount()==n+1);REQUIRE(m.find("fx",id)->number("threshold")==-24);REQUIRE(m.command("undo"));REQUIRE(m.processorParameters("fx",id)[0].number("value")==-18);REQUIRE(!m.command("fx.set",id,"invented",1));for(auto type:{"Parametric EQ","Reverb","Delay","Saturate","Bitcrush","Convolution","Filter"}){REQUIRE(m.command("fx.add","main",type));REQUIRE(!m.processorParameters("fx",m.records("fx").back().id).empty());}++groups;
}
static void coupledAndSliceGestures(){
 Model free;free.command("patch.load","keys");auto neighbour=free.find("zone","k55p")->number("lo");REQUIRE(free.gesture("zone:k48p:free-hi",0,53));REQUIRE(free.gesture("zone:k48p:free-hi",1,55));REQUIRE(free.gesture("zone:k48p:free-hi",2,55));REQUIRE(free.find("zone","k48p")->number("hi")==55);REQUIRE(free.find("zone","k55p")->number("lo")==neighbour);REQUIRE(free.command("undo"));REQUIRE(free.find("zone","k48p")->number("hi")==53);
 Model m;m.command("patch.load","kit");auto count=m.undoCount();REQUIRE(m.gesture("cutoff",0,6800));REQUIRE(m.gesture("cutoff",1,2400));REQUIRE(m.command("parameter.preview","resonance","",.8));REQUIRE(m.gesture("cutoff",3,2400));REQUIRE(m.number("cutoff")==6800);REQUIRE(m.number("resonance")==.24);REQUIRE(m.undoCount()==count);REQUIRE(!m.command("parameter.preview","resonance","",.8));
 REQUIRE(m.gesture("slice:sl2:start",0,.25));REQUIRE(m.gesture("slice:sl2:start",1,.27));REQUIRE(m.gesture("slice:sl2:start",2,.27));REQUIRE(m.undoCount()==count+1);REQUIRE(m.find("slice","sl2")->number("start")==.27);REQUIRE(m.command("undo"));REQUIRE(m.find("slice","sl2")->number("start")==.25);REQUIRE(m.gesture("slice:sl2:end",0,.375));REQUIRE(m.gesture("slice:sl2:end",1,.32));REQUIRE(m.gesture("slice:sl2:end",3,.32));REQUIRE(m.find("slice","sl2")->number("end")==.375);++groups;
}
static void parameterMidiLearn(){
 Model m;m.command("patch.load","kit");REQUIRE(m.command("parameter.learn","cutoff"));REQUIRE(m.text("midi-learn")=="cutoff");REQUIRE(m.command("midi.receive","","",74));REQUIRE(m.find("parameter","cutoff")->number("midi-cc")==74);REQUIRE(m.text("midi-learn").empty());REQUIRE(m.command("midi.receive","74","",127));REQUIRE(m.number("cutoff")==20000);REQUIRE(m.command("undo"));REQUIRE(m.number("cutoff")==6800);REQUIRE(!m.command("midi.receive","999","",127));REQUIRE(m.command("parameter.learn","cutoff"));REQUIRE(m.command("parameter.learn-stop"));REQUIRE(m.text("midi-learn").empty());++groups;
}
static void routeConfiguration(){
 Model layout;layout.selectState("mod");REQUIRE(layout.command("route.group","destination"));REQUIRE(layout.text("route-grouping")=="destination");REQUIRE(!layout.command("route.group","invented"));REQUIRE(layout.command("route.expand","source:velocity-mod"));REQUIRE(layout.text("route-open:source:velocity-mod")=="0");REQUIRE(!layout.command("route.expand","source:unknown"));
 Model m;m.command("patch.load","kit");for(auto [action,value]:std::vector<std::pair<std::string,std::string>>{{"route.scope","shared"},{"route.combine","multiply"},{"route.rate","audio"},{"route.polarity","bipolar"},{"route.curve","s-curve"}}){REQUIRE(m.command(action,"filter-route",value));REQUIRE(!m.command(action,"filter-route","invented"));}REQUIRE(m.find("route","filter-route")->text("scope")=="shared");REQUIRE(m.find("route","filter-route")->text("combine")=="multiply");REQUIRE(m.find("route","filter-route")->text("rate")=="audio");REQUIRE(m.command("undo"));REQUIRE(m.find("route","filter-route")->text("curve")=="0");REQUIRE(m.command("modulator.set","lfo1","phase",.1));m.tick(.1);REQUIRE(m.find("modulator","lfo1")->number("phase")==.1);REQUIRE(m.command("modulator.set","lfo1","retrigger",1));REQUIRE(m.find("modulator","lfo1")->number("retrigger")==1);++groups;
}
static void zeroCrossingSnap(){
 Model m;auto p=wav();REQUIRE(m.command("asset.import","",p.string()));ready(m);REQUIRE(m.command("sample.snap-zero","","",1));REQUIRE(m.number("snap-zero")==1);REQUIRE(m.command("sample.set","region-start","",.4));REQUIRE(std::abs(m.number("region-start")-1./3)<.0001);REQUIRE(m.command("sample.snap-zero","","",0));REQUIRE(m.command("sample.set","region-start","",.4));REQUIRE(m.number("region-start")==.4);REQUIRE(m.command("undo"));REQUIRE(std::abs(m.number("region-start")-1./3)<.0001);std::filesystem::remove(p);++groups;
}
static void multiFileMapping(){
 auto original=wav();auto low=original.parent_path()/"Felt_C3_p.wav",high=original.parent_path()/"Felt_C4_f.wav";std::filesystem::copy_file(original,low,std::filesystem::copy_options::overwrite_existing);std::filesystem::copy_file(original,high,std::filesystem::copy_options::overwrite_existing);
 for(auto mode:{"sequential","root-velocity","stack","round-robin"}){Model m;REQUIRE(m.command("asset.import-many",mode,low.string()+"\n"+high.string(),48));REQUIRE(m.records("source").size()==2);REQUIRE(m.records("zone").size()==2);REQUIRE(m.undoCount()==1);ready(m);REQUIRE(m.undoCount()==1);auto first=m.records("zone")[0],second=m.records("zone")[1];if(std::string(mode)=="sequential"){REQUIRE(first.number("lo")==48);REQUIRE(second.number("lo")==49);}if(std::string(mode)=="root-velocity"){REQUIRE(first.number("root-note")==48);REQUIRE(second.number("root-note")==60);REQUIRE(first.number("hi")==54);REQUIRE(second.number("lo")==55);REQUIRE(first.number("vel-hi")==90);REQUIRE(second.number("vel-lo")==81);}if(std::string(mode)=="stack"){REQUIRE(m.text("selector-mode")=="stack");REQUIRE(first.number("lo")==0);REQUIRE(second.number("hi")==127);}if(std::string(mode)=="round-robin"){REQUIRE(m.text("selector-mode")=="round-robin");REQUIRE(first.number("lo")==48);REQUIRE(second.number("lo")==48);}REQUIRE(m.command("undo"));REQUIRE(m.records("source").empty());REQUIRE(m.records("zone").empty());REQUIRE(m.command("redo"));REQUIRE(m.records("source").size()==2);REQUIRE(m.records("source")[0].text("state")=="loaded");}
 std::filesystem::remove(original);std::filesystem::remove(low);std::filesystem::remove(high);++groups;
}
static void perSourceRegions(){
 Model history;history.command("patch.load","kit");REQUIRE(history.command("sample.mode","","loop"));REQUIRE(history.command("sample.set","fade-in","",.12));auto operation=history.records("history").back().id;REQUIRE(history.command("sample.history-bypass",operation));REQUIRE(history.command("asset.select","snare-source"));REQUIRE(history.command("asset.select","kick-source"));REQUIRE(history.number("fade-in")==0);REQUIRE(history.number("loop-enabled")==1);REQUIRE(history.command("sample.history-bypass",operation));REQUIRE(history.command("asset.select","snare-source"));REQUIRE(history.command("asset.select","kick-source"));REQUIRE(history.number("fade-in")==.12);REQUIRE(history.command("sample.history-remove",operation));REQUIRE(history.command("asset.select","snare-source"));REQUIRE(history.command("asset.select","kick-source"));REQUIRE(history.number("fade-in")==0);
 Model m;m.command("patch.load","kit");REQUIRE(m.command("sample.set","region-start","",.2));REQUIRE(m.command("sample.set","fade-in","",.1));REQUIRE(m.command("asset.select","snare-source"));REQUIRE(m.number("region-start")==0);REQUIRE(m.number("fade-in")==0);REQUIRE(m.command("sample.set","region-start","",.4));REQUIRE(m.command("asset.select","kick-source"));REQUIRE(m.number("region-start")==.2);REQUIRE(m.number("fade-in")==.1);
 auto p=wav();REQUIRE(m.command("asset.import","",p.string()));ready(m);auto source=m.text("selected-source");REQUIRE(m.peaks().size()==4);REQUIRE(m.command("asset.select","kick-source"));REQUIRE(m.peaks().size()==256);std::filesystem::remove(p);REQUIRE(m.command("asset.select",source));REQUIRE(m.peaks().size()==4);REQUIRE(m.peaks()[2].minimum==-1);REQUIRE(m.command("pad.select","","",36));REQUIRE(m.peaks().size()==256);REQUIRE(m.text("selected-source")=="kick-source");REQUIRE(m.command("asset.select",source));REQUIRE(m.number("region-start")==0);REQUIRE(m.command("asset.select","snare-source"));REQUIRE(m.number("region-start")==.4);++groups;
}
static void sourceDrops(){
 Model preview;preview.command("patch.load","kit");REQUIRE(preview.command("asset.group-toggle","Drums"));REQUIRE(preview.text("source-open:Drums")=="0");REQUIRE(!preview.command("asset.group-toggle","Absent"));REQUIRE(preview.command("asset.select","kick-source"));REQUIRE(preview.command("slice.preview","sl3"));REQUIRE(preview.text("selected-source")=="break-source");REQUIRE(preview.text("selected-slice")=="sl3");REQUIRE(preview.number("playhead")==.375);REQUIRE(preview.number("audition")==1);REQUIRE(preview.heldNotes().empty());REQUIRE(!preview.command("slice.preview","absent"));
 Model layer;layer.command("patch.load","kit");layer.command("zone.select","snS");REQUIRE(layer.command("layer.add","sl2","New layer",38));auto inserted=layer.find("zone",layer.text("selected-zone"));REQUIRE(inserted->text("group")=="drums");REQUIRE(inserted->text("source")=="break-source");REQUIRE(inserted->number("region-start")==.25);REQUIRE(layer.command("slice.map","","",60));REQUIRE(layer.records("zone").back().text("source")=="break-source");REQUIRE(layer.records("zone").back().number("region-start")==.875);
 Model assignment;assignment.command("patch.load","kit");assignment.command("asset.select","kick-source");REQUIRE(assignment.command("tree.assign","kick","sl2"));REQUIRE(assignment.find("zone","kick")->text("source")=="break-source");REQUIRE(assignment.find("zone","kick")->number("region-start")==.25);REQUIRE(assignment.find("zone","kick")->number("region-end")==.375);REQUIRE(assignment.command("tree.assign","patch","sl3"));auto assigned=assignment.text("selected-zone");REQUIRE(assignment.find("zone",assigned)->text("source")=="break-source");REQUIRE(assignment.find("zone",assigned)->number("region-start")==.375);REQUIRE(assignment.find("zone",assigned)->number("region-end")==.5);
 Model m;m.command("patch.load","kit");auto zones=m.records("zone").size();REQUIRE(m.command("zone.assign","kick","keys-source"));REQUIRE(m.find("zone","kick")->text("source")=="keys-source");REQUIRE(m.command("undo"));REQUIRE(m.find("zone","kick")->text("source")=="kick-source");REQUIRE(m.command("pad.assign","60","keys-source"));REQUIRE(m.records("zone").size()==zones+1);REQUIRE(!m.selectCandidates(60,100).empty());REQUIRE(m.command("undo"));REQUIRE(m.records("zone").size()==zones);REQUIRE(m.command("zone.assign","kick","sl2"));REQUIRE(m.find("zone","kick")->number("region-start")==.25);REQUIRE(m.find("zone","kick")->number("region-end")==.375);REQUIRE(!m.command("pad.assign","999","keys-source"));REQUIRE(!m.command("zone.assign","kick","unknown"));++groups;
}
static void candidateControls(){
 Model gesture;gesture.command("patch.load","kit");gesture.command("zone.select","snS");REQUIRE(gesture.gesture("crossfade-width",0,8));REQUIRE(gesture.gesture("crossfade-width",1,12));REQUIRE(gesture.gesture("crossfade-width",3,12));REQUIRE(gesture.find("zone","snS")->number("vel-hi")==95);REQUIRE(gesture.undoCount()==0);
 Model m;m.command("patch.load","kit");REQUIRE(m.command("layer.set","snS","gain",-2));REQUIRE(m.find("zone","snS")->number("gain")==-2);REQUIRE(m.command("layer.set","snS","pan",.4));REQUIRE(m.command("layer.set","snS","pitch",12));REQUIRE(m.command("layer.output","snS","Snare 5/6"));REQUIRE(m.find("zone","snS")->text("output")=="Snare 5/6");REQUIRE(m.command("undo"));REQUIRE(m.find("zone","snS")->text("output").empty());REQUIRE(m.command("zone.select","snS"));REQUIRE(m.command("selector.crossfade","","linear",12));REQUIRE(m.find("zone","snS")->number("vel-hi")==101);REQUIRE(m.find("zone","snH")->number("vel-lo")==90);REQUIRE(m.command("undo"));REQUIRE(m.find("zone","snS")->number("vel-hi")==95);++groups;
}
static void renderConfiguration(){
 Model m;m.command("patch.load","kit");REQUIRE(m.autosamplerParameters().size()==6);REQUIRE(m.number("autosampler:lo")==36);REQUIRE(m.command("autosampler.configure","","lo",60));REQUIRE(m.command("autosampler.configure","","hi",63));REQUIRE(m.command("autosampler.configure","","step",3));REQUIRE(m.command("autosampler.configure","","layers",2));REQUIRE(m.command("autosampler.configure","","rr",2));auto count=m.records("source").size();REQUIRE(m.command("autosampler.start","kick-source"));ready(m);REQUIRE(m.records("source").size()==count+8);REQUIRE(m.records("source").back().text("origin")=="kick-source");REQUIRE(m.records("source").back().number("root-note")==63);REQUIRE(m.command("undo"));REQUIRE(m.records("source").size()==count);REQUIRE(m.command("freeze.configure","","mode",0)==false);REQUIRE(m.command("freeze.configure","src","mode"));REQUIRE(m.command("freeze.configure","","tail",3));REQUIRE(m.command("freeze.start","kick-source"));ready(m);REQUIRE(m.find("source","kick-source")->text("freeze-mode")=="src");REQUIRE(m.find("source","kick-source")->number("freeze-tail")==3);REQUIRE(m.command("sample.unfreeze","kick-source"));REQUIRE(m.find("source","kick-source")->text("kind")=="sample");++groups;
}
static void operationStack() {
 Model operations;operations.command("patch.load","kit");REQUIRE(operations.command("sample.history-add","","reverse"));REQUIRE(operations.number("reversed")==1);auto reverse=operations.records("history").back().id;REQUIRE(operations.command("sample.history-bypass",reverse));REQUIRE(operations.number("reversed")==0);REQUIRE(operations.command("sample.history-bypass",reverse));REQUIRE(operations.number("reversed")==1);REQUIRE(operations.command("sample.set","fade-in","",.1));auto first=operations.records("history").back().id;REQUIRE(operations.command("sample.set","fade-in","",.2));REQUIRE(operations.command("sample.history-move",first,"",1));REQUIRE(operations.number("fade-in")==.1);REQUIRE(operations.command("undo"));REQUIRE(operations.number("fade-in")==.2);REQUIRE(operations.command("sample.history-add","","fade-out",.05));REQUIRE(operations.number("fade-out")==.05);
 Model m;m.command("patch.load","kit");REQUIRE(m.command("sample.set","","fade-in",0.12));auto history=m.records("history").back().id;REQUIRE(m.command("sample.history-select",history));REQUIRE(m.text("selected-history")==history);REQUIRE(m.command("sample.history-select",history));REQUIRE(m.text("selected-history").empty());
 REQUIRE(m.command("inherit.override","drums","cutoff",2222));REQUIRE(m.command("inherit.override","drums","pan",0.2));REQUIRE(m.command("inherit.reset","drums"));REQUIRE(!m.find("override","drums:cutoff"));REQUIRE(!m.find("override","drums:pan"));REQUIRE(m.command("undo"));REQUIRE(m.find("override","drums:cutoff"));REQUIRE(m.find("override","drums:pan"));
 auto source=m.text("selected-source");auto sources=m.records("source").size();REQUIRE(m.command("sample.history-collapse",source));REQUIRE(m.text("collapse-state")=="running");ready(m);REQUIRE(m.text("collapse-state")=="done");REQUIRE(m.records("source").size()==sources+1);REQUIRE(m.text("selected-source")!=source);REQUIRE(m.records("history").size()==1);REQUIRE(m.records("history").front().number("baseline")==1);REQUIRE(!m.command("sample.history-bypass",m.records("history").front().id));REQUIRE(!m.command("sample.history-remove",m.records("history").front().id));REQUIRE(!m.command("sample.history-move",m.records("history").front().id,"",-1));REQUIRE(m.command("undo"));REQUIRE(m.records("source").size()==sources);REQUIRE(m.text("selected-source")==source);REQUIRE(m.records("history").size()==1);++groups;
}
static void encodedParameterTargets(){
 Model modulation;modulation.selectState("mod");REQUIRE(modulation.command("route.add","filter-env","modulator:lfo1:rate",.4));REQUIRE(modulation.command("parameter.set","modulator:lfo1:rate","",4));REQUIRE(modulation.find("modulator","lfo1")->number("rate")==4);REQUIRE(modulation.command("parameter.set","lfo1-depth","",.7));REQUIRE(modulation.find("modulator","lfo1")->number("depth")==.7);REQUIRE(modulation.command("modulator.select","filter-env"));REQUIRE(modulation.command("route.select","lfo1:pitch"));REQUIRE(modulation.text("selected-modulator")=="lfo1");
 Model m;m.command("patch.load","kit");REQUIRE(m.command("fx.add","drums","Compressor"));auto owner=m.records("fx").back().id;std::string target="fx:"+owner+":threshold";REQUIRE(m.parameterInfo(target)->number("default")==-18);REQUIRE(m.command("parameter.set",target,"",-30));REQUIRE(m.find("fx",owner)->number("threshold")==-30);REQUIRE(m.command("parameter.reset",target));REQUIRE(m.find("fx",owner)->number("threshold")==-18);REQUIRE(m.command("route.add","lfo1",target,.25));REQUIRE(m.command("macro.bind","tone",target,.3));REQUIRE(m.command("parameter.learn",target));REQUIRE(m.command("midi.receive","74","",127));REQUIRE(m.command("midi.receive","74","",0));REQUIRE(m.find("fx",owner)->number("threshold")==-60);REQUIRE(m.command("parameter.set","pad:38:pan","",.5));REQUIRE(m.command("parameter.reset","pad:38:pan"));REQUIRE(m.find("pad","38")->number("pan")==0);REQUIRE(!m.parameterInfo("pad:60:pan"));REQUIRE(!m.parameterInfo("fx:absent:threshold"));REQUIRE(!m.parameterInfo("fx:"+owner+":invented"));REQUIRE(m.command("parameter.host",target,"",1));REQUIRE(m.parameterInfo(target)->number("host")==1);++groups;
}
static void typedSourceCards(){
 Model hybrid;hybrid.command("patch.load","hybrid");REQUIRE(hybrid.find("module","lush-voice"));REQUIRE(hybrid.processorParameters("module","lush-voice").size()==6);REQUIRE(hybrid.processorParameters("module","lush-voice")[0].number("default")==-6);REQUIRE(hybrid.processorParameters("module","lush-voice")[3].number("value")==.34);REQUIRE(hybrid.find("source","lush"));REQUIRE(hybrid.find("source","lush")->text("kind")=="synth-patch");REQUIRE(hybrid.command("asset.select","lush"));REQUIRE(hybrid.text("selected-source")=="lush");REQUIRE(hybrid.command("asset.preview","lush"));REQUIRE(hybrid.command("sample.stop"));Model guide;guide.selectState("voice");REQUIRE(guide.find("source","lush"));REQUIRE(guide.find("source","lush")->text("kind")=="synth-patch");
 Model m;m.command("patch.load","kit");for(auto [name,count,mode,field]:std::vector<std::tuple<std::string,int,std::string,std::string>>{{"Noise",2,"pink","gain"},{"Oscillator",4,"square","detune"},{"Sampler",4,"loop","start"},{"Synth patch",4,"drone","brightness"}}){REQUIRE(m.command("module.add","voice",name));auto id=m.records("module").back().id;REQUIRE(m.processorParameters("module",id).size()==count);REQUIRE(m.processorParameters("module",id)[0].number("default")==-4);REQUIRE(m.command("module.mode",id,mode));REQUIRE(m.find("module",id)->text("mode")==mode);REQUIRE(!m.command("module.mode",id,"invalid"));REQUIRE(m.command("module.set",id,field,.25));REQUIRE(m.find("module",id)->number(field)==.25);REQUIRE(m.command("undo"));REQUIRE(m.command("undo"));REQUIRE(m.find("module",id)->text("mode")!=mode);}++groups;
}
static void treeStructure(){
 Model m;m.command("patch.load","kit");REQUIRE(m.command("fx.add","drums","Compressor"));auto fxCount=m.records("fx").size();auto zones=m.records("zone").size();REQUIRE(m.command("tree.duplicate","drums"));REQUIRE(m.records("zone").size()==zones+7);auto copy=m.text("selected-id");REQUIRE(m.records("fx").size()==fxCount+1);REQUIRE(m.records("fx").back().text("parent")==copy);std::size_t copiedZones=0;for(auto& zone:m.records("zone"))if(zone.text("group")==copy)++copiedZones;REQUIRE(copiedZones==7);REQUIRE(m.command("undo"));REQUIRE(m.records("zone").size()==zones);REQUIRE(m.command("tree.move","kick","keys"));REQUIRE(m.find("zone","kick")->text("group")=="keys");REQUIRE(m.command("undo"));REQUIRE(m.find("zone","kick")->text("group")=="drums");REQUIRE(m.command("tree.add","keys","Nested group",1));auto nested=m.text("selected-id");REQUIRE(m.command("tree.move","snare",nested));REQUIRE(m.find("tree","snareS")->number("depth")==4);REQUIRE(m.find("zone","snS")->text("group")==nested);REQUIRE(m.command("tree.delete","snare"));REQUIRE(!m.find("zone","snS"));REQUIRE(!m.find("zone","snH"));REQUIRE(!m.find("zone","snHB"));REQUIRE(m.command("undo"));REQUIRE(m.find("zone","snHB"));++groups;
}
static void sourceRemovalAndAudition(){
 Model m;m.command("patch.load","kit");REQUIRE(m.command("tree.audition","break"));REQUIRE(m.heldNotes().empty());REQUIRE(m.text("selected-source")=="break-source");REQUIRE(m.records("event").back().text("label").find("24")!=std::string::npos);REQUIRE(!m.command("tree.audition","sources"));auto count=m.records("source").size();REQUIRE(m.command("asset.remove","break-source"));REQUIRE(m.records("source").size()==count-1);REQUIRE(m.records("slice").empty());for(auto& zone:m.records("zone"))REQUIRE(zone.text("source")!="break-source");REQUIRE(m.text("selected-source")!="break-source");REQUIRE(m.command("undo"));REQUIRE(m.records("source").size()==count);REQUIRE(m.records("slice").size()==8);REQUIRE(m.text("selected-source")=="break-source");REQUIRE(m.peaks().size()==256);REQUIRE(!m.command("asset.remove","unknown"));++groups;
}
static void routingInheritance(){
 Model m;m.command("patch.load","kit");REQUIRE(m.undoLabel().empty());REQUIRE(m.redoLabel().empty());REQUIRE(!m.gesture("unregistered",0,0));REQUIRE(m.command("scope.select","","group"));REQUIRE(m.text("scope")=="group");REQUIRE(m.outputFor("kick")=="Main 1/2");REQUIRE(m.command("routing.output","drums","Drums 3/4"));REQUIRE(m.outputFor("kick")=="Drums 3/4");REQUIRE(m.outputFor("snareS")=="Drums 3/4");REQUIRE(m.command("routing.output","snare","Snare 5/6"));REQUIRE(m.outputFor("snareS")=="Snare 5/6");REQUIRE(m.command("routing.inherit","snare"));REQUIRE(m.outputFor("snareS")=="Drums 3/4");REQUIRE(m.command("undo"));REQUIRE(m.outputFor("snareS")=="Snare 5/6");REQUIRE(!m.redoLabel().empty());REQUIRE(!m.undoLabel().empty());REQUIRE(m.command("routing.output","kick","main"));REQUIRE(m.outputFor("kick")=="Main 1/2");++groups;
}
static void importPersistence(){
 auto file=wav();Model m;REQUIRE(m.command("asset.import","",file.string()));ready(m);REQUIRE(m.records("zone").front().number("lo")==0);REQUIRE(m.records("zone").front().number("hi")==127);REQUIRE(m.records("zone").front().number("root-note")==60);REQUIRE(m.number("root-note")==60);auto definition=m.definition();Model restored;REQUIRE(restored.importDefinition(definition));REQUIRE(restored.peaks().size()==4);REQUIRE(restored.peaks()[2].minimum==-1);REQUIRE(restored.undoCount()==0);std::filesystem::remove(file);Model missing;REQUIRE(missing.importDefinition(definition));REQUIRE(missing.text("asset-state")=="missing");REQUIRE(missing.peaks().empty());++groups;
}
static void modulatorLifecycle(){
 Model pads;pads.command("patch.load","kit");REQUIRE(pads.command("route.add","lfo1","pad:38:pan",.25));REQUIRE(pads.records("route").back().text("destination")=="pad:38:pan");REQUIRE(!pads.command("route.add","lfo1","pad:60:pan",.25));REQUIRE(!pads.command("route.add","lfo1","pad:38:invented",.25));
 Model shapes;shapes.selectState("mod");for(auto [id,shape]:std::vector<std::pair<std::string,std::string>>{{"lfo1","sh"},{"filter-env","ahdsr"},{"random-note","smooth"},{"velocity-mod","exp"}}){REQUIRE(shapes.command("modulator.shape",id,shape));REQUIRE(shapes.find("modulator",id)->text("shape")==shape);REQUIRE(shapes.command("undo"));REQUIRE(shapes.find("modulator",id)->text("shape")!=shape);}REQUIRE(!shapes.command("modulator.shape","lfo1","adsr"));REQUIRE(!shapes.command("modulator.shape","absent","sine"));
 Model m;m.selectState("mod");REQUIRE(m.command("modulator.set","filter-env","attack",80));REQUIRE(m.number("filter-attack")==80);REQUIRE(m.command("undo"));REQUIRE(m.number("filter-attack")==4);REQUIRE(m.command("parameter.set","filter-decay","",90));REQUIRE(m.find("modulator","filter-env")->number("decay")==90);REQUIRE(m.command("modulator.set","lfo1","rate",-20));REQUIRE(m.find("modulator","lfo1")->number("rate")==.01);REQUIRE(!m.command("route.set","filter-route","fabricated",20));
 REQUIRE(m.command("amp.detach"));REQUIRE(!m.find("route","amp-default"));REQUIRE(m.text("amp-status")=="detached");REQUIRE(m.command("undo"));REQUIRE(m.find("route","amp-default"));REQUIRE(m.command("amp.replace","filter-env"));REQUIRE(m.find("route","amp-default")->text("source")=="filter-env");REQUIRE(m.command("amp.restore"));REQUIRE(m.find("route","amp-default")->text("source")=="amp-env");REQUIRE(!m.command("modulator.delete","amp-env"));++groups;
}
static void reloadAndStates() {
 Model m;m.command("patch.load","kit");m.command("zone.set","kick","lo",35);REQUIRE(m.text("reload-state")=="pending");REQUIRE(m.command("patch.reload-fail"));ready(m);REQUIRE(m.text("reload-state")=="failed");REQUIRE(!m.records("zone").empty());REQUIRE(m.command("patch.reload"));ready(m);REQUIRE(m.text("reload-state")=="ready");for(auto id:Model::stateIds()){REQUIRE(m.selectState(id)); REQUIRE(m.text("state-id")==id);}REQUIRE(Model::stateIds().size()==30);
 REQUIRE(m.selectState("sample"));REQUIRE(m.records("zone").size()==27);REQUIRE(m.records("modulator").size()==12);REQUIRE(m.records("route").size()==14);auto source=m.find("source",m.text("selected-source"));REQUIRE(source&&source->text("name")=="felt_C4_f.wav");REQUIRE(source->number("duration")==4.82);REQUIRE(m.number("region-start")==0.012);REQUIRE(m.number("region-end")==0.94);REQUIRE(m.peaks().size()==600);REQUIRE(m.selectState("loop"));REQUIRE(m.number("loop-start")==0.55);REQUIRE(m.number("loop-end")==0.82);REQUIRE(m.number("loop-crossfade")==0.025);REQUIRE(m.selectState("fx"));REQUIRE(m.find("fx","comp"));REQUIRE(m.records("fx").size()==9);REQUIRE(m.processorParameters("fx","comp").size()==6);REQUIRE(m.selectState("voice"));REQUIRE(m.number("cutoff")==2400);++groups;
}
static void cancelActiveGesture() {
 Model m;REQUIRE(m.command("patch.load","hybrid"));auto before=*m.find("module","lush-voice");auto history=m.undoCount();
 REQUIRE(m.gesture("module:lush-voice:detune",0,static_cast<float>(.34)));REQUIRE(m.gesture("module:lush-voice:detune",1,.8));REQUIRE(m.command("gesture.cancel"));
 REQUIRE(m.find("module","lush-voice")->fields==before.fields);REQUIRE(m.undoCount()==history);REQUIRE(!m.gesture("module:lush-voice:detune",2,.8));REQUIRE(m.command("gesture.cancel"));REQUIRE(m.undoCount()==history);
 REQUIRE(m.command("patch.load","kit"));before=*m.find("zone","kick");auto pending=m.number("pending-count");REQUIRE(m.gesture("zone:kick:free-hi",0,36));REQUIRE(m.gesture("zone:kick:free-hi",1,39));REQUIRE(m.command("gesture.cancel"));REQUIRE(m.find("zone","kick")->fields==before.fields);REQUIRE(m.number("pending-count")==pending);REQUIRE(m.undoCount()==0);
 auto definition=m.definition();REQUIRE(m.gesture("region-start",0,0));REQUIRE(m.gesture("region-start",1,.2));REQUIRE(m.command("gesture.cancel"));REQUIRE(m.definition()==definition);REQUIRE(m.records("history").empty());++groups;
}
static void mappingInsertAndGap(){Model m;REQUIRE(m.command("patch.load","keys"));REQUIRE(m.command("zone.select","k48p"));REQUIRE(m.command("zone.context-select","k48f","86",50));REQUIRE(m.text("selected-zone")=="k48p");auto old=*m.find("zone","k48p");auto count=m.records("zone").size();REQUIRE(m.command("zone.insert","k48p","",51));REQUIRE(m.records("zone").size()==count+1);REQUIRE(m.find("zone","k48p")->number("hi")==50);auto created=m.find("zone",m.text("selected-zone"));REQUIRE(created&&created->number("lo")==51&&created->number("hi")==53&&created->text("source").empty());REQUIRE(m.noteOn(51,1,"empty-zone"));REQUIRE(m.text("diagnostic-reason")=="empty");m.noteOff(51,"empty-zone");REQUIRE(m.command("undo"));REQUIRE(m.find("zone","k48p")->fields==old.fields);REQUIRE(m.command("patch.load","kit"));REQUIRE(m.command("zone.add-gap","","80",45));created=m.find("zone",m.text("selected-zone"));REQUIRE(created&&created->number("lo")==43&&created->number("hi")==45&&created->number("root-note")==45);REQUIRE(created->text("source").empty());++groups;}
static void selectorAxesAndPolicies(){Model m;REQUIRE(m.command("patch.load","kit"));REQUIRE(m.command("selector.axis","","macro"));REQUIRE(m.text("selector-axis")=="macro");REQUIRE(m.command("selector.source","tone"));auto selected=m.selectCandidates(38,127);REQUIRE(selected.size()==1&&selected.front()=="snS");REQUIRE(m.command("macro.set","tone","",1));selected=m.selectCandidates(38,1);REQUIRE(selected.size()==2);REQUIRE(m.command("selector.axis","","mod"));REQUIRE(m.command("selector.source","lfo1"));REQUIRE(!m.command("selector.source","tone"));REQUIRE(m.command("modulator.set","lfo1","phase",.25));REQUIRE(m.command("modulator.set","lfo1","depth",1));m.tick(0);selected=m.selectCandidates(38,1);REQUIRE(selected.size()==2);REQUIRE(m.command("modulator.set","lfo1","phase",.75));m.tick(0);selected=m.selectCandidates(38,127);REQUIRE(selected.size()==1&&selected.front()=="snS");REQUIRE(m.command("selector.axis","","key"));selected=m.selectCandidates(38,127);REQUIRE(selected.size()==1&&selected.front()=="snS");REQUIRE(!m.command("selector.axis","","invalid"));REQUIRE(m.command("selector.axis","","vel"));REQUIRE(m.command("selector.mode","","random"));REQUIRE(m.command("selector.no-repeat","","",0));std::string previous;bool repeated=false;for(int i=0;i<64;++i){selected=m.selectCandidates(38,127);REQUIRE(selected.size()==1);repeated=repeated||selected.front()==previous;previous=selected.front();}REQUIRE(repeated);REQUIRE(m.command("selector.mode","","weighted"));REQUIRE(m.command("selector.no-repeat","","",1));previous.clear();for(int i=0;i<40;++i){selected=m.selectCandidates(38,127);REQUIRE(selected.size()==1);REQUIRE(selected.front()!=previous);previous=selected.front();}REQUIRE(m.command("layer.set","snHB","weight",0));for(int i=0;i<10;++i)REQUIRE(m.selectCandidates(38,127).front()=="snH");REQUIRE(m.command("selector.lock","","",0));REQUIRE(m.number("take-lock")==0);REQUIRE(m.command("undo"));REQUIRE(m.number("take-lock")==1);++groups;}
static void modulatorResetDefaults(){Model m;REQUIRE(m.command("patch.load","kit"));auto initial=m.number("filter-attack");auto descriptor=m.parameterInfo("modulator:filter-env:attack");REQUIRE(descriptor&&descriptor->number("default")==initial);REQUIRE(m.command("parameter.set","modulator:filter-env:attack","",40));REQUIRE(m.command("parameter.reset","modulator:filter-env:attack"));REQUIRE(m.number("filter-attack")==initial);REQUIRE(m.find("modulator","filter-env")->number("attack")==initial);++groups;}
static void articulationConfiguration(){Model m;REQUIRE(m.command("patch.load","kit"));REQUIRE(m.command("articulation.select","","stac"));REQUIRE(m.text("articulation")=="stac");REQUIRE(!m.command("articulation.select","","unregistered"));REQUIRE(m.command("articulation.release","","",0));REQUIRE(m.number("release-trigger")==0);REQUIRE(m.command("undo"));REQUIRE(m.number("release-trigger")==1);REQUIRE(m.command("articulation.pedal","","",0));REQUIRE(m.number("pedal-aware-release")==0);++groups;}
static void scopedProcessorReorder(){Model m;REQUIRE(m.selectState("fx"));REQUIRE(m.command("fx.move","eqr","",-1));auto before=m.definition();auto count=m.undoCount();REQUIRE(m.command("fx.move","eqr","",-1));REQUIRE(m.definition()==before);REQUIRE(m.undoCount()==count);++groups;}
static void pitchAnalysisRootAndFine(){Model m;REQUIRE(m.command("patch.load","kit"));REQUIRE(m.command("asset.select","kick-source"));REQUIRE(m.command("parameter.set","fine","",-7));auto old=*m.find("source","kick-source");auto before=m.undoCount();REQUIRE(m.command("analysis.start","pitch"));m.tick(1);REQUIRE(m.text("analysis-state")=="done");REQUIRE(m.command("analysis.apply"));REQUIRE(m.number("root-note")==60);REQUIRE(m.number("fine")==3);REQUIRE(m.find("source","kick-source")->number("root-note")==60);REQUIRE(m.undoCount()==before+1);REQUIRE(m.command("undo"));REQUIRE(m.number("fine")==-7);REQUIRE(m.find("source","kick-source")->fields==old.fields);++groups;}
static void pitchAnalysisSourceOwnership(){Model m;REQUIRE(m.command("patch.load","kit"));REQUIRE(m.command("asset.select","kick-source"));auto kick=*m.find("source","kick-source");auto keys=*m.find("source","keys-source");REQUIRE(m.command("analysis.start","pitch"));m.tick(1);REQUIRE(m.command("asset.select","keys-source"));auto before=m.undoCount();REQUIRE(!m.command("analysis.apply"));REQUIRE(m.undoCount()==before);REQUIRE(m.find("source","kick-source")->fields==kick.fields);REQUIRE(m.find("source","keys-source")->fields==keys.fields);++groups;}
static void rootNoteGestures(){Model m;REQUIRE(m.command("patch.load","kit"));auto source=*m.find("source","kick-source");auto initial=m.number("root-note");auto count=m.undoCount();REQUIRE(m.gesture("root-note",0,initial));REQUIRE(m.gesture("root-note",1,60));REQUIRE(m.gesture("root-note",1,61));REQUIRE(m.gesture("root-note",2,61));REQUIRE(m.number("root-note")==61);REQUIRE(m.find("source","kick-source")->number("root-note")==61);REQUIRE(m.undoCount()==count+1);REQUIRE(m.records("history").size()==1);REQUIRE(m.command("undo"));REQUIRE(m.number("root-note")==initial);REQUIRE(m.find("source","kick-source")->fields==source.fields);REQUIRE(m.records("history").empty());REQUIRE(m.gesture("root-note",0,initial));REQUIRE(m.gesture("root-note",1,72));REQUIRE(m.gesture("root-note",3,72));REQUIRE(m.number("root-note")==initial);REQUIRE(m.find("source","kick-source")->fields==source.fields);REQUIRE(m.undoCount()==count);++groups;}
int main(){try{rootNoteGestures();mappingInsertAndGap();selectorAxesAndPolicies();modulatorResetDefaults();articulationConfiguration();scopedProcessorReorder();pitchAnalysisRootAndFine();pitchAnalysisSourceOwnership();cancelActiveGesture();history();patch();assets();analysis();mapping();processing();lifecycle();domainGestureAndDiagnostics();newGestureContracts();edgeCases();sourceBrowserAndAssignment();typedProcessors();coupledAndSliceGestures();parameterMidiLearn();routeConfiguration();zeroCrossingSnap();multiFileMapping();perSourceRegions();sourceDrops();candidateControls();renderConfiguration();operationStack();encodedParameterTargets();typedSourceCards();treeStructure();sourceRemovalAndAudition();routingInheritance();importPersistence();modulatorLifecycle();reloadAndStates();std::cout<<groups<<" groups, "<<assertions<<" assertions passed\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
