#include "AdvancedSamplerDomainPages.h"
#include "ui/advanced-sampler/engine/Bindings.h"
#include "ui/slint/host/ValueCodec.h"
#include <slint-testing.h>
#include <slint-platform.h>
#include <iostream>
#include <stdexcept>
int main(){int checks=0;try{
 slint::testing::init();auto w=AdvancedSamplerDomainPages::create();auto b=dandrum::sampler::bindWindowSession<Session>(w);dandrum::slint_ui::bind_value_codec<ParsedValue>(w->global<ValueCodec>());const auto& s=w->global<Session>();w->show();
 auto require=[&](bool ok,std::string text){++checks;if(!ok)throw std::runtime_error(text);};
 auto settle=[&](){slint::invoke_from_event_loop([]{slint::quit_event_loop();});slint::run_event_loop();};
 auto action=[&](std::string label){settle();auto elements=slint::testing::ElementHandle::find_by_accessible_label(w,label);for(auto&e:elements)if(e.accessible_role()==slint::language::AccessibleRole::Button){e.invoke_accessible_default_action();settle();return;}throw std::runtime_error("Missing native button: "+label);};
 auto value=[&](std::string label,std::string val){settle();auto elements=slint::testing::ElementHandle::find_by_accessible_label(w,label);for(auto&e:elements)if(e.accessible_role()==slint::language::AccessibleRole::Slider){e.set_accessible_value(val.c_str());settle();return;}throw std::runtime_error("Missing native value: "+label);};
 auto drag=[&](std::string label,float dx,float dy){settle();auto elements=slint::testing::ElementHandle::find_by_accessible_label(w,label);if(elements.empty())throw std::runtime_error("Missing native handle: "+label);auto element=elements[0];auto position=element.absolute_position();auto size=element.size();slint::LogicalPosition start{{position.x+size.width/2,position.y+size.height/2}},end{{start.x+dx,start.y+dy}};w->window().dispatch_pointer_press_event(start,slint::PointerEventButton::Left);w->window().dispatch_pointer_move_event(end);w->window().dispatch_pointer_release_event(end,slint::PointerEventButton::Left);settle();};
 require(s.invoke_command("patch.load","keys","",0),"load Keys for corner drag");auto hi=b->model()->find("zone","k48p")->number("vel-hi");auto history=b->model()->undoCount();drag("Velocity high Felt C3 p",0,-12);require(b->model()->find("zone","k48p")->number("vel-hi")>hi,"Actual mapping velocity edge drag updates native range");require(b->model()->undoCount()==history+1,"Velocity drag is one undo step");s.invoke_command("undo","","",0);require(b->model()->find("zone","k48p")->number("vel-hi")==hi,"Velocity drag undo restores exact range");
 settle();auto freeHandles=slint::testing::ElementHandle::find_by_accessible_label(w,"Velocity high Felt C3 p");require(!freeHandles.empty(),"Free edit has actual zone handle");auto freePosition=freeHandles[0].absolute_position();auto freeSize=freeHandles[0].size();slint::LogicalPosition body{{freePosition.x+freeSize.width/2,freePosition.y+24}},edge{{freePosition.x+freeSize.width-2,freePosition.y+24}},moved{{edge.x+20,edge.y}};w->window().dispatch_pointer_press_event(body,slint::PointerEventButton::Left);w->window().dispatch_pointer_release_event(body,slint::PointerEventButton::Left);w->window().dispatch_key_press_event("\x10");auto freeHistory=b->model()->undoCount();w->window().dispatch_pointer_press_event(edge,slint::PointerEventButton::Left);w->window().dispatch_pointer_move_event(moved);w->window().dispatch_key_release_event("\x10");w->window().dispatch_pointer_release_event(moved,slint::PointerEventButton::Left);settle();require(b->model()->find("zone","k48p")->number("hi")>53,"Actual Shift edge drag changes selected range");require(b->model()->find("zone","k55p")->number("lo")==54,"Shift edge drag preserves neighbour");require(b->model()->undoCount()==freeHistory+1,"Releasing Shift mid-drag still commits one captured gesture");s.invoke_command("undo","","",0);require(b->model()->find("zone","k48p")->number("hi")==53,"Captured free drag undo restores key range");
 require(s.invoke_command("patch.load","keys","",0),"Load Keys shortcut fixture");settle();auto shortcutHandles=slint::testing::ElementHandle::find_by_accessible_label(w,"Velocity high Felt C3 p");auto shortcutPoint=shortcutHandles[0].absolute_position();auto shortcutSize=shortcutHandles[0].size();slint::LogicalPosition shortcutBody{{shortcutPoint.x+shortcutSize.width/2,shortcutPoint.y+24}};w->window().dispatch_pointer_press_event(shortcutBody,slint::PointerEventButton::Left);w->window().dispatch_pointer_release_event(shortcutBody,slint::PointerEventButton::Left);w->window().dispatch_key_press_event("\x11");w->window().dispatch_key_press_event("c");w->window().dispatch_key_release_event("c");w->window().dispatch_key_press_event("\x10");auto beforePaste=b->model()->records("zone").size();w->window().dispatch_key_press_event("v");w->window().dispatch_key_release_event("v");w->window().dispatch_key_release_event("\x10");w->window().dispatch_key_release_event("\x11");settle();require(b->model()->records("zone").size()==beforePaste+2,"Actual Ctrl+C / Ctrl+Shift+V copies selected key range as layers");auto keyboardCopy=b->model()->find("zone",b->model()->text("selected-zone"));require(keyboardCopy&&keyboardCopy->number("lo")==54,"Keyboard paste defaults after selected high key");w->window().dispatch_key_press_event("\x10");w->window().dispatch_key_press_event("\x7f");w->window().dispatch_key_release_event("\x7f");w->window().dispatch_key_release_event("\x10");settle();require(b->model()->records("zone").size()==beforePaste+1,"Shift+Delete removes selected mapping leaving a gap");require(s.get_sounding_notes()->row_count()==0,"Mapping shortcuts produce no PC notes");
 require(s.invoke_command("patch.load","keys","",0),"load Keys");auto zones=s.get_zones()->row_count();action("+ Zone");require(s.get_zones()->row_count()==zones+1,"Mapping Add changes native zone inventory");s.invoke_command("undo","","",0);require(s.get_zones()->row_count()==zones,"Mapping Add undo restores inventory");action("By root");require(b->model()->records("zone").front().number("lo")==0,"Root mapping uses actual root ranges");
 s.invoke_command("patch.load","kit","",0);w->set_page("layers");action("Selection policy Round robin");require(s.get_selector_mode()=="round-robin","Layer selector buttons change actual native policy");action("Selection policy Weighted");require(s.get_selector_mode()=="weighted","Weighted policy reaches backend");action("+ Layer");require(s.get_zones()->row_count()==16,"Layer Add creates a real candidate");
 s.invoke_command("zone.select","snS","",0);s.invoke_command("selector.mode","","velocity",0);value("Crossfade width","12");require(b->model()->find("zone","snS")->number("vel-hi")==101,"Crossfade control edits actual soft boundary");require(b->model()->find("zone","snH")->number("vel-lo")==90,"Crossfade control edits actual hard boundary");value("Gain Snare soft","-3 dB");require(b->model()->find("zone","snS")->number("gain")==-3,"Candidate gain edits actual dB");auto gainHistory=b->model()->undoCount();drag("Gain Snare soft",0,-14);require(b->model()->find("zone","snS")->number("gain")>-3,"Physical candidate gain scrub retains gesture state");require(b->model()->undoCount()==gainHistory+1,"Candidate scrub coalesces one Undo");s.invoke_command("undo","","",0);require(b->model()->find("zone","snS")->number("gain")==-3,"Candidate scrub Undo restores dB");
 auto softRange=b->model()->find("zone","snS")->number("vel-hi");auto rangeHistory=b->model()->undoCount();drag("Velocity range high Snare soft",14,0);require(b->model()->find("zone","snS")->number("vel-hi")>softRange,"Actual crossfade graph endpoint edits selected candidate velocity");require(b->model()->undoCount()==rangeHistory+1,"Crossfade endpoint is one Undo");s.invoke_command("undo","","",0);require(b->model()->find("zone","snS")->number("vel-hi")==softRange,"Crossfade endpoint undo restores exact boundary");
 w->set_page("voice");auto modules=s.get_modules()->row_count();action("Add voice module");require(s.get_modules()->row_count()==modules+1,"Voice Add creates native processor");value("Cutoff","1234 Hz");require(b->model()->number("cutoff")==1234,"Voice knob typed action updates native actual units");s.invoke_command("undo","","",0);require(b->model()->number("cutoff")==6800,"Voice value undo restores model");action("Voice policy Mono");require(b->model()->text("voice-policy")=="mono","Voice policy persists");
 w->set_page("mod");auto routes=s.get_routes()->row_count();action("+ Route");require(s.get_routes()->row_count()==routes+1,"Modulation add connects native source/destination");action("Add modulator");require(s.get_modulators()->row_count()==6,"Native modulator inventory changes");action("Filter envelope");value("Modulator attack","80 ms");require(b->model()->number("filter-attack")==80,"Mod envelope control edits actual Voice ADSR");action("Detach amplitude");require(!b->model()->find("route","amp-default"),"Default amplitude route detaches");action("Restore default amplitude");require(b->model()->find("route","amp-default"),"Default amplitude lifecycle restores real route");
 require(s.invoke_command("state.select","mod","",0),"Guide routes for grouping");action("Group routes Destination");require(s.get_route_grouping()=="destination","Actual destination grouping updates native presentation state");require(s.get_route_groups()->row_count()==9,"Destination grouping displays each native destination once");action("Group routes Source");require(s.get_route_groups()->row_count()==12,"Source grouping displays each native source once");action("Toggle route group Velocity");require(!s.get_route_groups()->row_data(4)->expanded,"Group disclosure hides child route rows");action("Toggle route group Velocity");action("Add destination Velocity");require(w->get_last_context()=="modulator-destination"&&w->get_last_target()=="velocity-mod","Grouped Add destination sends actual native source target to parameter picker");action("LFO 1");action("Modulator shape S&H");require(b->model()->find("modulator","lfo1")->text("shape")=="sh","S&H choice persists actual native shape");value("Modulator fade in","150 ms");require(b->model()->find("modulator","lfo1")->number("fade-in")==150,"LFO fade in changes native timing");action("Velocity");action("Modulator shape Exp");require(b->model()->find("modulator","velocity-mod")->text("shape")=="exp","Performance curve choice persists");value("Modulator input low","25 %");require(b->model()->find("modulator","velocity-mod")->number("in-low")==.25,"Performance input endpoint uses normalized units");s.invoke_command("patch.load","kit","",0);
 w->set_page("routing");s.invoke_command("selection.set","kick","",0);action("Drums 3/4");require(b->model()->find("tree","kick")->text("output")=="Drums 3/4","Routing output changes native sound");value("Reverb","25 %");require(b->model()->find("send","kick:Reverb")->number("value")==0.25,"Send knob creates actual normalized native send");action("Inherit");require(s.get_selected_output()=="inherit","Inherit clears local output");
 w->set_page("fx");auto before=s.get_modules()->row_count();action("+ Effect");require(s.get_modules()->row_count()==before+1,"FX Add changes real chain");action("Bypass effect Parametric EQ");require(b->model()->find("fx","eq")->number("bypassed")==1,"FX bypass persists");
 action("+ Compressor");auto comp=b->model()->records("fx").back().id;value("Threshold","-24 dB");require(b->model()->find("fx",comp)->number("threshold")==-24,"Typed processor control changes actual dB threshold");s.invoke_command("undo","","",0);require(b->model()->processorParameters("fx",comp)[0].number("value")==-18,"Processor undo restores default threshold");auto graphHistory=b->model()->undoCount();drag("Processor graph Compressor",24,0);require(b->model()->find("fx",comp)->number("threshold")>-18,"Actual processor graph drag updates typed native threshold");require(b->model()->undoCount()==graphHistory+1,"Processor graph drag coalesces one Undo");s.invoke_command("undo","","",0);require(b->model()->processorParameters("fx",comp)[0].number("value")==-18,"Graph drag undo restores threshold");
 {s.invoke_command("state.select","mod","",0);w->set_page("mod");action("Route scope Shared");require(b->model()->find("route","filter-route")->text("scope")=="shared","Native route scope persisted");action("Combine Multiply");require(b->model()->find("route","filter-route")->text("combine")=="multiply","Native combine persisted");for(auto rate:std::vector<std::string>{"Control","Block","Audio"}){action("Update rate "+rate);std::string id=rate=="Control"?"control":rate=="Block"?"block":"audio";require(b->model()->find("route","filter-route")->text("rate")==id,"Native route rate persisted "+id);}action("Select route Amp envelope to Amp gain");require(b->model()->text("selected-route")=="amp-default","Native route selection updates selected editor");action("Filter envelope");action("Replace with selected");require(b->model()->find("route","amp-default")->text("source")=="filter-env","Native amplitude replacement uses selected source");s.invoke_command("undo","","",0);require(b->model()->find("route","amp-default")->text("source")=="amp-env","Native amplitude replacement Undo restores default source");}
{s.invoke_command("state.select","vel","",0);w->set_page("layers");action("Crossfade curve Linear");require(b->model()->text("crossfade-curve")=="linear","Native linear choice persists");require(b->model()->find("zone","snS")->number("vel-hi")>b->model()->find("zone","snH")->number("vel-lo"),"Actual curve enables crossfade overlapping velocity ranges");action("Crossfade curve No crossfade");require(b->model()->number("crossfade-width")==0&&b->model()->text("crossfade-curve")=="none","Native No-crossfade sets hard split");require(b->model()->find("zone","snS")->number("vel-hi")+1==b->model()->find("zone","snH")->number("vel-lo"),"Native hard split has no overlap or gap");s.invoke_command("undo","","",0);require(b->model()->text("crossfade-curve")=="linear","No-crossfade Undo restores preceding curve");}
{s.invoke_command("state.select","routing","",0);s.invoke_command("selection.set","drums","",0);w->set_page("routing");action("Snare");require(b->model()->text("selected-id")=="snare","Actual output assignment row selects real node");}
 {w->set_page("mapping");s.invoke_command("patch.load","keys","",0);s.invoke_command("zone.select","k48p","",0);settle();auto edges=slint::testing::ElementHandle::find_by_accessible_label(w,"Velocity high Felt C3 p");require(!edges.empty(),"Existing native mapping supplies context target geometry");auto p=edges[0].absolute_position();auto size=edges[0].size();slint::LogicalPosition point{{p.x+size.width*.4f,p.y+24}};w->window().dispatch_pointer_press_event(point,slint::PointerEventButton::Right);w->window().dispatch_pointer_release_event(point,slint::PointerEventButton::Right);settle();action("Insert zone at D3");require(b->model()->find("zone","k48p")->number("hi")==49,"Actual Insert at hovered D3 changes old range");}
{s.invoke_command("state.select","vel","",0);w->set_page("layers");action("Blend axis Macro");require(b->model()->text("selector-axis")=="macro","Actual blend axis changes native selection configuration");}
{s.invoke_command("patch.load","kit","",0);w->set_page("mod");action("Filter envelope");settle();auto fields=slint::testing::ElementHandle::find_by_accessible_label(w,"Modulator attack");require(!fields.empty(),"Actual modulator attack exists");for(auto field:fields)if(field.accessible_role()==slint::language::AccessibleRole::Slider){field.set_accessible_value("40 ms");settle();require(b->model()->find("modulator","filter-env")->number("attack")==40,"Actual selected Filter attack changes before Reset");auto p=field.absolute_position();auto size=field.size();slint::LogicalPosition point{{p.x+size.width*.5f,p.y+size.height*.8f}};w->window().dispatch_pointer_press_event(point,slint::PointerEventButton::Middle);w->window().dispatch_pointer_release_event(point,slint::PointerEventButton::Middle);settle();break;}require(b->model()->find("modulator","filter-env")->number("attack")==2,"Actual modulator Reset restores ordinary preset attack2ms");}
{s.invoke_command("state.select","fx","",0);w->set_page("fx");settle();require(!slint::testing::ElementHandle::find_by_accessible_label(w,"Group inserts").empty(),"Native FX displays guide group insert hierarchy");require(!slint::testing::ElementHandle::find_by_accessible_label(w,"FX busses").empty(),"Native FX displays independent send bus hierarchy");}
 {s.invoke_command("state.select","mapping","",0);w->set_page("mapping");action("Staccato · C♯0");require(s.get_articulation()=="stac","Actual keyswitch articulation persists");s.invoke_command("undo","","",0);require(s.get_articulation()=="sus","Articulation Undo restores Sustain");action("Release trigger");require(!s.get_release_trigger(),"Actual release-trigger toggle persists");action("Pedal-aware release");require(!s.get_pedal_aware_release(),"Actual pedal release toggle persists");}
 {s.invoke_command("state.select","vel","",0);w->set_page("layers");action("Selection policy Round robin");require(slint::testing::ElementHandle::find_by_accessible_label(w,"Blend axis Macro").empty(),"Round-robin view excludes Velocity blend axis");action("Lock takes across mics and layers");require(!s.get_take_lock(),"Actual take-lock toggle persists");s.invoke_command("undo","","",0);require(s.get_take_lock(),"Take-lock Undo restores native policy");action("No immediate repeat");require(!s.get_no_immediate_repeat(),"Actual repeat toggle persists");s.invoke_command("undo","","",0);require(s.get_no_immediate_repeat(),"Repeat Undo restores native policy");action("Selection policy Velocity");require(slint::testing::ElementHandle::find_by_accessible_label(w,"No immediate repeat").empty(),"Velocity view excludes round-robin take policy");action("Blend axis Modulator");action("Blend modulator LFO 1");require(s.get_selector_axis()=="mod"&&s.get_selector_source()=="lfo1","Actual Modulator axis/source persists");action("Blend axis Key");require(s.get_selector_axis()=="key","Actual Key axis persists");action("Blend axis Velocity");require(s.get_selector_axis()=="vel","Actual Velocity axis restores");}
 w->hide();std::cout<<"PASS: "<<checks<<" actual native domain page checks\n";return 0;
 }catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
