import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
test('all 24 supplied states are reached through ordinary actions and mock switches, with actual loading and recovery',async({page})=>{
 test.setTimeout(60000);const errors=[],captures=[],out=process.env.TRIGGER_CAPTURE;
 page.on('pageerror',e=>errors.push(e.message));if(out)await mkdir(out,{recursive:true});
 const capture=async(id,label)=>{captures.push({id,label,box:await page.getByTestId('trigger-editor').boundingBox()});if(out)await page.getByTestId('trigger-editor').screenshot({path:out+'/'+id+'.png'});};
 const status=()=>page.getByRole('banner').getByRole('status'),log=()=>page.getByRole('button',{name:'Log',exact:true}),tab=label=>page.getByRole('tab',{name:label}).click();
 await page.goto('/');await expect(page.getByText('Drop samples here',{exact:true})).toBeVisible();await capture('01','Empty');
 await page.getByRole('button',{name:/^Patch/}).click();await page.getByRole('button',{name:'Load Felt Kit',exact:true}).click();await expect(status()).toContainText('Ready');
 await page.getByRole('button',{name:'Browser',exact:true}).click();await expect(page.getByLabel('Search samples')).toBeVisible();await capture('02','Loaded with browser');await page.getByRole('button',{name:'Close browser',exact:true}).click();
 await capture('03','Sample editing');await page.getByRole('radio',{name:'Sustain loop',exact:true}).click();await expect(page.getByRole('spinbutton',{name:'Loop start',exact:true})).toBeVisible();await capture('04','Loop editing');
 await tab(/^Slices/);await expect(page.getByText('8 selected',{exact:true})).toHaveCount(0);await capture('05','Slice editing');
 await page.getByRole('button',{name:'Detect transients',exact:true}).click();await expect(page.getByText(/Detecting transients/)).toBeVisible();await capture('18','Analysis running');await expect(page.getByText('15 transients found',{exact:true})).toBeVisible();await capture('06','Transient analysis done');
 await log().click();await page.getByRole('switch',{name:'Fail next analysis',exact:true}).click();await log().click();await page.getByRole('button',{name:'Detect transients',exact:true}).click();await expect(page.getByText('Transient detection failed',{exact:true})).toBeVisible();await capture('19','Analysis failed');
 await tab('Mapping');await expect(page.getByRole('button',{name:'Map by root',exact:true})).toBeVisible();await capture('07','Key map');
 await tab('Layers');await expect(page.getByRole('button',{name:'Velocity',exact:true})).toHaveAttribute('aria-pressed','true');await capture('08','Velocity layers');
 await page.locator('[data-node="snare-hard"] [role="option"]').click();await expect(page.getByRole('button',{name:'Round robin',exact:true})).toHaveAttribute('aria-pressed','true');await capture('09','Round robin');
 await tab('Voice');await capture('10','Voice shaping');await tab(/^Modulation/);await capture('11','Modulation');await page.locator('[data-ctx="macro|Tone"]').click();await expect(page.getByRole('button',{name:'Learn MIDI',exact:true})).toBeVisible();await capture('12','Macro editing');
 await tab('Routing');await capture('13','Routing');await tab('Effects');await capture('14','Effects');
 await page.locator('[data-node="k60"] [role="option"]').click();await tab('Sample');await log().click();await page.getByRole('switch',{name:'Mark file missing',exact:true}).click();await log().click();await expect(page.getByText(/sample unavailable/)).toBeVisible();await capture('15','Missing asset');
 const locate=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Locate file…',exact:true}).click();await (await locate).setFiles({name:'felt_C4_f.wav',mimeType:'audio/wav',buffer:Buffer.from('mock sample')});await expect(page.getByText('Loading felt_C4_f.wav',{exact:true})).toBeVisible();await capture('17','Loading');await expect(page.getByRole('slider',{name:'Region start',exact:true})).toBeVisible();
 await page.getByLabel('Import sample files').setInputFiles({name:'drum_take.m4a',mimeType:'audio/mp4',buffer:Buffer.from('unsupported mock')});await expect(page.getByText('File was not loaded',{exact:true})).toBeVisible();await capture('16','Unsupported import');
 for(const [id,size,w,h] of [['20','Min',820,560],['21','Default',1200,800],['22','Expanded',1600,1000]]){await page.getByRole('radio',{name:size,exact:true}).click();await expect(page.getByTestId('trigger-editor')).toHaveCSS('width',w+'px');await expect(page.getByTestId('trigger-editor')).toHaveCSS('height',h+'px');await capture(id,size);}
 await page.getByLabel('Import sample files').setInputFiles([{name:'felt_C4_p.wav',mimeType:'audio/wav',buffer:Buffer.from('mock')},{name:'felt_C4_f.wav',mimeType:'audio/wav',buffer:Buffer.from('mock')}]);await expect(page.getByRole('region',{name:'Import mapping',exact:true})).toBeVisible();await capture('23','Multi-file drop');await page.keyboard.press('Escape');await expect(page.getByRole('region',{name:'Import mapping',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Collapse',exact:true}).click();await expect(page.getByTestId('trigger-editor')).toHaveCSS('width','900px');await expect(page.getByTestId('trigger-editor')).toHaveCSS('height','126px');await capture('24','Compact');expect(captures.length).toBe(24);expect(errors).toEqual([]);if(out)await writeFile(out+'/actions.json',JSON.stringify(captures,null,2));
});
