include(FetchContent)
set(JIVE_BUILD_TEST_RUNNER OFF CACHE BOOL "" FORCE)
set(JIVE_BUILD_DEMO_RUNNER OFF CACHE BOOL "" FORCE)
set(JIVE_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(JIVE_BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(JIVE
    URL https://github.com/ImJimmi/JIVE/archive/89d5787a762e674ee8b7141031a99e6743948f05.tar.gz
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(JIVE)

include(${CMAKE_CURRENT_LIST_DIR}/SlintDependency.cmake)
