// Presentation data ported from the supplied Trigger reference.
export function frameModelProjection(context) {
  let {S, cur, page, layout, isMin, isExp, perf, W, H, scale, browser, empty, drop, missing, unsup, loading, loop, mode, tr, treeW, inspW, pageCanon, pianoPeaks, seamA, seamB, partialPeaks, nm, tree, assets, sampleKnobGroups, meta, sp, slices, sliceRows, transients, zones, rels, relSegs, relList, M, menuItems, menuTitle, dropRules, selModes, modeDescs, isRRlike, vLo, vHi, vW, vCurve, vx, xa, xb, vSoftPts, vHardPts, gSoft, gHard, gStops, softRange, hardRange, cands, rrSeq, chain, cutoffMods, voiceSecs, envH, envs, routes, routeGroups, me, modSrcs, routeRows, busses, outputs, insertLayers, fxLayers, macros, insp, crumbs, PV, pvPos, playSlice, srcGroups, hSel, hist, hOn, KM, kmenus, CM, DM, status} = context;
  const hints = { sample: 'Drag markers to edit · double-click a value to type · Ctrl+wheel zooms · Space auditions', slices: 'Click to select · Shift/Ctrl adds · drag a marker to move it · M adds · Delete removes · ← → step', mapping: 'Edges push neighbours · Shift-drag to overlap (crossfade) or gap · right-click to insert, copy, paste, delete · Ctrl+C / Ctrl+V', layers: 'Drag rows to reorder · drop files to add · click M/S to mute or solo', voice: 'Right-click or M on a control to assign modulation · double-click resets', mod: 'Drag the amount bar · Alt-drag inverts · Delete removes the selected route', routing: 'Inherit follows the parent group · set a bus to override', fx: 'Drag modules to reorder · dot bypasses · + adds a processor' };
  const tabs = [
    { id: 'sample', label: 'Sample', icon: 'level' }, { id: 'slices', label: 'Slices', icon: 'slice', badge: '8' }, { id: 'mapping', label: 'Mapping', icon: 'keyboard' },
    { id: 'layers', label: 'Layers', icon: 'layers' }, { id: 'voice', label: 'Voice', icon: 'settings' }, { id: 'mod', label: isMin ? 'Mod' : 'Modulation', icon: 'modulate', badge: '14' },
    { id: 'routing', label: 'Routing', icon: 'pan' }, { id: 'fx', label: 'Effects', icon: 'variation' },
  ].map(t => isMin ? { id: t.id, label: t.label, badge: t.badge } : t);
  const showBrowser = browser && !isMin;
  const isSample = page === 'sample' && !empty && !drop;

  return {
    states: S.map(s => ({ label: s[1], sel: s[0] === cur[0], go: () => this.go(s[0]) })),
    stateLabel: cur[1], ann: this.state.ann, toggleAnn: (v) => this.setState({ ann: v }),
    W, H, scale, outW: Math.round(W * scale), outH: Math.round(H * scale),
    layout, isMin, notMin: !isMin, isExp, headH: isMin ? 38 : 44, patchW: isMin ? 150 : 220,
    layoutOpts: [{ id: 'min', label: 'Min', title: '820 × 560' }, { id: 'default', label: 'Default', title: '1200 × 800' }, { id: 'exp', label: 'Expanded', title: '1600 × 1000' }],
    setLayout: (v) => this.setState({ layout: v }),
    patchName: empty || drop ? 'Untitled' : 'Felt Kit', status, voicesText: empty || drop ? 'Voices 0 / 32' : 'Voices 6 / 32',
    meterLv: empty ? [-90, -90] : [-14, -15],
    tabs, page, goPage: (id) => this.go(pageCanon[id]),
    browser, browserLabel: isMin ? '' : 'Browser', toggleBrowser: () => this.setState({ browser: !browser }),
    banner: missing || unsup, missing, unsup,
    gridCols: treeW + 'px minmax(0,1fr) ' + inspW + 'px',
    showTree: !isMin && !showBrowser, showBrowser, tree, assets, browserFilter: [{ id: 'all', label: 'All' }, { id: 'smp', label: 'Samples' }, { id: 'ir', label: 'IRs' }, { id: 'fav', label: 'Favourites' }],
    isEmpty: empty, isDrop: drop,
    dropOpts: [
      { name: 'One per key', sug: false, desc: 'Each file on its own key from C3 upward.', border: 'var(--dd-line-2)', cells: [1,2,3,4,5,6].map(c => ({ col: c, row: '1 / 3', bg: 'var(--dd-ink-5)' })) },
      { name: 'By root + velocity', sug: true, desc: '6 roots × p / f. Keys between roots filled; p below f.', border: 'var(--dd-vermilion)', cells: [1,3,5].flatMap(c => [{ col: c + ' / span 2', row: 1, bg: 'var(--dd-vermilion-lo)' }, { col: c + ' / span 2', row: 2, bg: 'var(--dd-ink-6)' }]) },
      { name: 'Stack', sug: false, desc: 'All files play together on every key.', border: 'var(--dd-line-2)', cells: [1,2].map(r => ({ col: '1 / 7', row: r, bg: 'var(--dd-ink-5)' })) },
      { name: 'Round robin', sug: false, desc: 'One key; files cycle per hit.', border: 'var(--dd-line-2)', cells: [{ col: '3 / 5', row: '1 / 3', bg: 'var(--dd-ink-5)' }] },
    ],
    isSample, isLoading: isSample && loading, waveReady: isSample && !loading, loop,
    assetName: 'felt_C4_f.wav', playMode: loop ? 'sus' : 'once',
    playOpts: [{ id: 'once', label: 'Once' }, { id: 'gated', label: 'Gated' }, { id: 'loop', label: 'Loop' }, { id: 'pp', label: 'Ping-pong' }, { id: 'sus', label: 'Sustain loop' }],
    pianoPeaks, partialPeaks, seamA, seamB, waveH: isMin ? 150 : isExp ? 340 : loop ? 190 : 250,
    loopS: loop ? 0.55 : undefined, loopE: loop ? 0.82 : undefined, xfade: loop ? 0.025 : undefined, cursor: PV && PV.target === 'sample' ? PV.from + (PV.to - PV.from) * pvPos : 0.31,
    waveLabel: 'felt_C4_f.wav · 4.820 s', meta: isMin ? meta.slice(0, 3) : meta, sampleKnobGroups, fmtNote: (v) => Math.round(v) + ' ' + nm(Math.round(v)),
    isSlices: page === 'slices' && !empty && !drop, slices, sliceRows, transients, trShown: tr === 'done', trDone: tr === 'done', trRun: tr === 'run', trFail: tr === 'fail',
    sliceWaveH: isMin ? 120 : isExp ? 260 : 190, divOpts: [{ id: 'even', label: 'Even' }, { id: 'grid', label: 'Grid' }],
    isMapping: page === 'mapping' && !empty && !drop, zones, zoneSel: this.state.zoneSel, selZone: (id) => this.setState({ zoneSel: id }), chZones: (z, id) => this.chZones(z, id), mapRef: this.mapRef, winRef: this.winRef, onMapCtx: (e) => this.onMapCtx(e), onMapMove: (e) => this.onMapMove(e),
    relSegs, relList, noRel: !rels.length, dragShift: !!this.state.dragShift, mapNote: this.state.mapNote || '', clipLabel: this.state.clip ? this.state.clip.label : '',
    menuOpen: !!M, menuX: M ? M.x : 0, menuY: M ? M.y : 0, menuItems, menuTitle, closeMenu: () => this.setState({ menu: null }), closeMenuCtx: (e) => { e.preventDefault(); this.setState({ menu: null }); }, keymapH: isMin ? 180 : isExp ? 420 : 300, dropRules,
    isLayers: page === 'layers' && !empty && !drop, layerCtx: isRRlike ? 'Snare › Hard · note 38 D2 · vel 96–127' : 'Snare · note 38 D2 · vel 1–127', selModes, modeDesc: modeDescs[mode], isVel: mode === 'vel', vSoftStops: gStops(false, gSoft), vHardStops: gStops(true, gHard), vHardTc: gHard > 0.6 ? 'var(--dd-ink-0)' : 'var(--dd-paper-1)', vXa: vW ? xa : vLo - 1.5, vXb: vW ? xb : vLo - 1.4, onVelDown: (e) => this.onVelDown(e), vSoftPts, vHardPts,
    vSoftLabel: 'Soft · ' + softRange, vHardLabel: 'Hard · ' + hardRange,
    vBandL: vx(vLo - 0.5), vBandR: vx(Math.max(vLo - 0.5, vHi + 0.5)), vBandW: Math.max(0, vx(vHi + 0.5) - vx(vLo - 0.5)), vMid: vx((vLo + vHi) / 2), vBandBg: vW ? 'var(--dd-vermilion-wash)' : 'transparent', vLast: vx(74),
    vAxis: 'last hit vel 74 · ' + (74 >= vLo && 74 <= vHi ? 'both layers' : 74 < vLo ? 'Soft' : 'Hard'),
    vXfText: vW ? vLo + '–' + vHi + ' · ' + vW + ' steps' : 'Off · hard split at ' + vLo, vXfW: vW, vNoXf: !vW,
    setVelW: (n) => { const w = Math.max(0, Math.min(60, Math.round(n || 0))), mid = (vLo + vHi) / 2; const lo = Math.max(2, Math.round(mid - (w - 1) / 2)); this.setState({ vHardLo: lo, vSoftHi: Math.min(126, lo + w - 1) }); },
    velNoXf: () => { const mid = Math.round((vLo + vHi) / 2); this.setState({ vHardLo: mid + 1, vSoftHi: mid }); },
    vCurve, setVelCurve: (v) => this.setState({ vCurve: v }), vCurveOpts: [{ id: 'eq', label: 'Equal power' }, { id: 'lin', label: 'Linear' }], isRR: isRRlike, cands, rrSeq, weightHead: mode === 'wrand' ? 'Weight' : 'Share',
    resetOpts: [{ id: 'never', label: 'Never' }, { id: 'transport', label: 'On play' }, { id: 'bar', label: 'Each bar' }],
    isVoice: page === 'voice' && !empty && !drop, chain, voiceSecs, voiceCols: isMin ? 'repeat(2,minmax(0,1fr))' : isExp ? 'repeat(5,minmax(0,1fr))' : 'repeat(3,minmax(0,1fr))', envs, envH,
    envCols: isMin ? 'minmax(0,1fr)' : 'minmax(0,1fr) minmax(0,1fr) 200px',
    envShapes: [{ id: 'adsr', label: 'ADSR' }, { id: 'ahdsr', label: 'AHDSR' }, { id: 'multi', label: 'Multi' }],
    polyOpts: [{ id: 'poly', label: 'Poly' }, { id: 'mono', label: 'Mono' }, { id: 'legato', label: 'Legato' }],
    isMod: page === 'mod' && !empty && !drop, routes, modSrcs, cutoffMods: (this.knobMods.Cutoff || cutoffMods).filter(m => m.slot), modCols: 'minmax(0,1fr)',
    assigning: !!this.state.dragMod, endModDrag: () => this.setState({ dragMod: null, dropOver: null }),
    onKnobOver: (e) => { if (!this.state.dragMod) return; const t = e.target.closest && e.target.closest('[data-knob]'); if (t) { e.preventDefault(); e.dataTransfer.dropEffect = 'link'; } const lab = t ? t.getAttribute('data-knob') : null; if (lab !== this.state.dropOver) this.setState({ dropOver: lab }); },
    onKnobLeave: (e) => { if (this.state.dropOver && !(e.relatedTarget && e.relatedTarget.closest && e.relatedTarget.closest('[data-knob]'))) this.setState({ dropOver: null }); },
    onKnobDrop: (e) => { const d = this.state.dragMod; const t = e.target.closest && e.target.closest('[data-knob]'); if (!d || !t) return; e.preventDefault(); const lab = t.getAttribute('data-knob'); const add = Object.assign({}, this.state.added || {}); add[lab] = (add[lab] || []).concat([{ slot: d.slot || undefined, depth: 0.25, source: d.name }]); this.setState({ added: add, dragMod: null, dropOver: null, modNote: 'Added route ' + d.name + ' → ' + lab + ' +25% · drag the ring or open the popup to set depth' }); },
    cutoffRing: this.state.dropOver === 'Cutoff' ? '0 0 0 1px var(--dd-vermilion)' : 'none', cutoffPop: !this.state.dragMod, groupByOpts: [{ id: 'src', label: 'Source' }, { id: 'dst', label: 'Destination' }],
    isRouting: page === 'routing' && !empty && !drop, routeRows, busses, outputs, routeCols: isExp ? 'minmax(0,1fr) minmax(600px,1.2fr)' : 'minmax(0,1fr)',
    isFx: page === 'fx' && !empty && !drop, insertLayers, fxLayers,
    kTight: { style: { padding: '1px 1px', gap: 1, minWidth: 0, '--type-label': '11px', '--type-micro': '11px' } },
    me, meH: isMin ? 64 : isExp ? 110 : 84,
    notPerf: !perf, perfLabel: perf ? 'Open editor' : 'Collapse', perfIcon: perf ? 'chevron-down' : 'chevron-right', togglePerf: () => this.setState({ perf: !perf, kmenu: null, menu: null }), macroSize: isMin && !perf ? 'sm' : 'md',
    crumbs, insp, macros, srcGroups, hist, hasHist: hist.length > 0, histCount: hist.filter(o => o.on).length + ' of ' + hist.length, histNote: hSel ? 'Click the operation again to show the result.' : 'Bottom to top. Uncheck to bypass, drag ⋮⋮ to reorder, click to edit.',
    hRs: hOn('trim') ? 0.012 : 0, hRe: hOn('trim') ? 0.94 : 1, hFi: hOn('fade') ? 0.004 : 0, hFo: hOn('fade') ? 0.08 : 0,
    onWaveClick: () => this.play('felt_C4_f.wav', { target: 'sample', from: hOn('trim') ? 0.012 : 0, to: hOn('trim') ? 0.94 : 1, dur: 3 }),
    onSliceWaveClick: (e) => { const r = e.currentTarget.getBoundingClientRect(), pos = (e.clientX - r.left) / r.width; let i = 0; sp.forEach((p, j) => { if (pos >= p) i = j; }); playSlice(i); },
    selSlice: this.state.selSlice ?? 2, sliceCursor: PV && PV.target === 'break' ? PV.from + (PV.to - PV.from) * pvPos : 0.29,
    endSrcDrag: () => this.setState({ dragSrc: null, nodeOver: null }),
    onNodeOver: (e) => { const d = this.state.dragSrc; if (!d) return; const t = e.target.closest && e.target.closest('[data-node]'); const id = t ? t.getAttribute('data-node') : null; const ok = id && this.dropInfo(id); if (ok) { e.preventDefault(); e.dataTransfer.dropEffect = 'copy'; } if ((ok ? id : null) !== this.state.nodeOver) this.setState({ nodeOver: ok ? id : null }); },
    onNodeDrop: (e) => { const d = this.state.dragSrc; const t = e.target.closest && e.target.closest('[data-node]'); if (!d || !t) return; const id = t.getAttribute('data-node'), info = this.dropInfo(id); if (!info) return; e.preventDefault(); const as = Object.assign({}, this.state.assigned || {}); as[id] = (as[id] || []).concat([{ name: d.name, kind: d.kind, role: info.role }]); this.setState({ assigned: as, dragSrc: null, nodeOver: null, modNote: 'Added ' + d.name + (d.kind === 'slice' ? ' (slice of amen_172.wav)' : '') + ' to ' + info.target + ' as ' + info.role }); },
    kmenuOpen: !!(KM || DM || CM),
    onRootCtx: (e) => { if (e.defaultPrevented) return; const knob=e.target.closest?.('[data-knob]');if(knob){e.preventDefault();const p=this.winPt(e,264,200);this.setState({kmenu:{...p,label:knob.dataset.knob,path:[]},cmenu:null,dmenu:null});return;}const t = e.target.closest && e.target.closest('[data-ctx]'); if (!t) return; e.preventDefault(); const [type, key] = t.getAttribute('data-ctx').split(/\|(.*)/s); const p = this.winPt(e, 264, 220); this.setState({ cmenu: { x: p.x, y: p.y, type, key }, kmenu: null, dmenu: null }); },
    onRootDown: (e) => { if (e.button !== 1) return; const t = e.target.closest && e.target.closest('[data-reset]'); if (!t) return; e.preventDefault(); e.stopPropagation(); const [kind, key] = t.getAttribute('data-reset').split(/\|(.*)/s); this.resetTarget(kind, key); },
    onAux: (e) => { if (e.button === 1) e.preventDefault(); },
    noUndo: !this.props.store.canUndo, noRedo: !this.props.store.canRedo,
    doUndo: () => this.undoStep(-1), doRedo: () => this.undoStep(1),
    undoTip: this.props.store.canUndo ? 'Undo ' + this.props.store.undoLabel + ' (Ctrl+Z)' : 'Nothing to undo',
    redoTip: this.props.store.canRedo ? 'Redo ' + this.props.store.redoLabel + ' (Ctrl+Shift+Z)' : 'Nothing to redo', kmenus, routeGroups, closeK: () => this.setState({ kmenu: null, dmenu: null, cmenu: null }), closeKCtx: (e) => { e.preventDefault(); this.setState({ kmenu: null, dmenu: null, cmenu: null }); },
    onKnobCtx: (e) => { const t = e.target.closest && e.target.closest('[data-knob]'); if (!t) return; e.preventDefault(); const p = this.winPt(e, 264, 160); this.setState({ kmenu: { x: p.x, y: p.y, label: t.getAttribute('data-knob'), path: [] } }); }, macroGap: isMin ? 8 : 12, macroPad: '8px 8px 2px', hint: this.state.dragSrc ? 'Drop ' + this.state.dragSrc.name + ' on a pad, layer or zone' + (this.state.nodeOver ? ' · ' + (this.dropInfo(this.state.nodeOver).role === 'new pad' ? 'new pad in Drums' : 'add to ' + this.dropInfo(this.state.nodeOver).target + ' as ' + this.dropInfo(this.state.nodeOver).role) : '') + ' · Esc cancels' : PV ? 'Previewing ' + PV.name : this.state.dragMod ? 'Assigning ' + this.state.dragMod.name + ' · drop on a highlighted control to add a route · Esc cancels' : this.state.modNote ? this.state.modNote : empty || drop ? 'Drop files anywhere in the window · Ctrl+O browses' : hints[page],
    idleHint:empty||drop?'Drop files anywhere in the window · Ctrl+O browses':hints[page],
    sizeText: W + ' × ' + H + (scale < 1 ? ' · preview ' + Math.round(scale * 100) + '%' : ''),
  };
}
