// Fonts are the original, licensed binaries shared by every DanDrum renderer.
// Import Tokens through this file so direct component consumers also embed fonts.
import "../design-system/fonts/Barlow/Barlow-Medium.ttf";
import "../design-system/fonts/Barlow/Barlow-SemiBold.ttf";
import "../design-system/fonts/Barlow/Barlow-Bold.ttf";
import "../design-system/fonts/BarlowSemiCondensed/BarlowSemiCondensed-Medium.ttf";
import "../design-system/fonts/BarlowSemiCondensed/BarlowSemiCondensed-SemiBold.ttf";
import "../design-system/fonts/BarlowSemiCondensed/BarlowSemiCondensed-Bold.ttf";
import "../design-system/fonts/JetBrainsMono/JetBrainsMono-Medium.ttf";
import "../design-system/fonts/JetBrainsMono/JetBrainsMono-SemiBold.ttf";
export { Tokens } from "tokens.slint";
